import { getDb } from './client'
import { studies, topicHubs, glossaryTerms } from './schema'

async function seedStudies() {
  const db = getDb()
  console.log('🌱 Seeding Wissensuniversum (Themen-Hubs + Studien + Glossar)...')

  // ── Themen-Hubs ─────────────────────────────────────────────────────────────
  const hubs = await db.insert(topicHubs).values([
    { slug: 'allergien',     name: 'Allergien & Unverträglichkeiten', description: 'Wissenschaftliche Studien zu Futterallergien, Nahrungsmittelunverträglichkeiten, Eliminationsdiäten und hypoallergenem Futter.', icon: '🤧', studyCount: 8, order: 1 },
    { slug: 'barf',          name: 'BARF vs. Verarbeitung',           description: 'Vergleichsstudien zwischen Rohfütterung (BARF), Trockenfutter und Nassfutter. Nährstoffprofile, mikrobiologische Sicherheit und Langzeiteffekte.', icon: '🥩', studyCount: 12, order: 2 },
    { slug: 'trockenfutter', name: 'Trockenfutter',                   description: 'Studien zu Kibble, kaltgepresstem Futter, Hygiene, Nährstoffdichte und Auswirkungen auf Zahngesundheit.', icon: '🥣', studyCount: 7, order: 3 },
    { slug: 'welpen',        name: 'Welpen-Ernährung',                description: 'Wachstum, Nährstoffbedarf, Entwicklungsphasen und langfristige Auswirkungen der Welpen-Ernährung auf die Gesundheit.', icon: '🐕', studyCount: 6, order: 4 },
    { slug: 'senioren',      name: 'Senioren & Longevity',            description: 'Alterungsprozess, Gelenkgesundheit, kognitive Funktion und Ernährungsstrategien für langes Hundeleben.', icon: '👴', studyCount: 5, order: 5 },
    { slug: 'uebergewicht',  name: 'Übergewicht',                     description: 'Kalorien, Fettgehalt, Gewichtsmanagement und metabolische Auswirkungen von Übergewicht bei Hunden.', icon: '⚖️', studyCount: 4, order: 6 },
    { slug: 'verdauung',     name: 'Verdauung & Mikrobiom',           description: 'Darmgesundheit, Probiotika, Präbiotika und die Rolle des Darmmikrobioms für die Hundegesundheit.', icon: '🦠', studyCount: 6, order: 7 },
    { slug: 'nachhaltigkeit',name: 'Nachhaltigkeit',                  description: 'Plant-based Diäten, Insektenprotein, Umwelt-Impact von Hundefutter und alternative Proteinquellen.', icon: '🌱', studyCount: 3, order: 8 },
  ]).returning()
  console.log(`✅ ${hubs.length} Themen-Hubs erstellt`)

  // ── Studien ──────────────────────────────────────────────────────────────────
  const studyData = [
    // ── Allergien ──────────────────────────────────────────────────────────────
    {
      slug: 'plant-based-diets-hunde-2024',
      title: 'Domestic dogs maintain clinical, nutritional, and hematological health outcomes when fed a commercial plant-based diet for a year',
      authors: ['Linde, A.', 'Lahiff, M.', 'Krantz, A.', 'Sharp, N.', 'Ng, T.T.', 'Melgarejo, T.'],
      year: 2024,
      journal: 'PLOS ONE',
      doi: '10.1371/journal.pone.0298942',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38639901',
      studyDesign: 'Prospektive Kohortenstudie',
      population: 'Klinisch gesunde erwachsene Haushunde, n=15',
      methodology: '12-monatige prospektive Studie mit 15 Hunden, die ein kommerzielles pflanzliches Hundefutter erhielten. Bewertung bei 0, 6 und 12 Monaten inklusive körperliche Untersuchung, Blutbild, Blutchemie, kardiale Biomarker, Plasma-Aminosäuren und Serum-Vitamine.',
      keyFindings: 'Klinisch gesunde Hunde können Gesundheit auf vollwertiger, ausgewogener pflanzlicher Ernährung (K9PBN) über 12 Monate aufrechterhalten. Keine signifikanten Unterschiede in klinischen, hämatologischen und ernährungsphysiologischen Parametern. Die umfassendste und längste K9PBN-Untersuchung bis dato.',
      limitations: 'Kleine Stichprobe (n=15). Alle Hunde aus einer Region (Los Angeles County). Kontrollgruppe mit Fleischfutter nur als Baseline, nicht als parallele Gruppe. Langzeiteffekte (>12 Monate) nicht untersucht.',
      bellaSummary: 'Diese Studie ist ein Game-Changer! 15 Hunde wurden ein Jahr lang nur mit pflanzlichem Futter gefüttert – und alle blieben gesund! Blutwerte, Herz, Verdauung: alles im grünen Bereich. Das Wichtigste: Das Futter muss von Tierärzten formuliert und "complete and balanced" sein. Wenn du pflanzlich füttern willst, such nach AAFCO/FEDIAF-zertifizierten Produkten. Aber: Frag immer deinen Tierarzt, besonders bei sensiblen Hunden!',
      evidenceStrength: 'hoch',
      tags: ['nachhaltigkeit', 'pflanzlich', 'protein', 'langzeit'],
      topicHub: 'nachhaltigkeit',
      relatedProducts: [],
    },
    {
      slug: 'raw-diets-microbiological-hazards-2019',
      title: 'Raw diets for dogs and cats: a review, with particular reference to microbiological hazards',
      authors: ['Davies, R.H.', 'Lawes, J.R.', 'Wales, A.D.'],
      year: 2019,
      journal: 'Veterinary Record',
      doi: '10.1136/vr.105317',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31492807',
      studyDesign: 'Systematic Review',
      population: 'Literaturübersicht (mehrere Studien)',
      methodology: 'Umfassende Review-Studie zu mikrobiologischen Risiken von Rohfutter (RMBDs) für Hunde und Katzen. Analyse von Studien zu Salmonellen, E. coli, Listerien, antimikrobieller Resistenzen und anderen zoonotischen Erregern.',
      keyFindings: 'Rohfutter zeigt konsistent hohe Belastung mit Salmonellen (typischerweise 5–20 % in frisch-gefrorenen kommerziellen Diäten). Enterobacteriaceae überschreiten häufig Hygiene-Schwellenwerte. Rohfutter-fütternde Hunde erhöhen das Risiko für Ausscheidung von antimikrobiell-resistenten Bakterien.',
      limitations: 'Review-Studie basiert auf heterogenen Primärstudien mit unterschiedlicher Methodik. Geografische Variationen nicht vollständig berücksichtigt.',
      bellaSummary: 'Diese Review-Studie ist ernüchternd: Rohfutter hat echte mikrobiologische Risiken. Salmonellen wurden in 5–20 % der getesteten Proben gefunden. Noch besorgniserregender: antimikrobiell-resistente Bakterien. Wenn du BARF füttern willst, musst du extrem auf Hygiene achten. Für Familien mit Kleinkindern oder immungeschwächten Personen würde ich eher zu verarbeitetem Futter raten.',
      evidenceStrength: 'hoch',
      tags: ['barf', 'hygiene', 'sicherheit', 'bakterien', 'resistenzen'],
      topicHub: 'barf',
      relatedProducts: [],
    },
    {
      slug: 'welpen-protein-bedarf-1990',
      title: 'Protein requirements of growing pups fed practical dry-type diets containing mixed-protein sources',
      authors: ['Case, L.P.', 'Carey, D.P.', 'Hirakawa, D.A.'],
      year: 1990,
      journal: 'Journal of Nutrition',
      doi: '10.1093/jn/120.9.1583',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/2337283',
      studyDesign: 'Comparative Study',
      population: 'Pointer-Welpen, n=unbekannt (3 Experimente)',
      methodology: 'Drei Experimente mit Pointer-Welpen zur Bestimmung des Proteinbedarfs. 8-wöchige Welpen erhielten Diäten mit verschiedenen Proteinquellen (Maisgluten, Sojabohnenmehl, Fleischknochenmehl). Messung von Wachstumsrate, Proteinverdaulichkeit und Blutwerten.',
      keyFindings: '8-wöchige Welpen benötigten 25,2 % Protein bei Mischprotein-Diät. Bei Ersatz durch minderwertiges Geflügelnebenprodukt stieg der Bedarf auf 27,5 % aufgrund verringerter Verdaulichkeit. 16-wöchige Welpen waren effizienter: nur 23 % Rohprotein benötigt.',
      limitations: 'Nur eine Rasse (Pointer). Spezifische Proteinquellen getestet, Ergebnisse nicht auf alle Quellen übertragbar. Kurze Studiendauer. Keine Langzeitbeobachtung.',
      bellaSummary: 'Diese klassische Studie zeigt: Welpen brauchen mehr Protein als erwachsene Hunde – 25–27 % bei 8 Wochen! Wichtig ist die Qualität: minderwertiges Protein war schlechter verdaulich. Ältere Welpen (16 Wochen) sind effizienter. Tipp: Achte auf hochwertiges Protein im Welpenfutter!',
      evidenceStrength: 'hoch',
      tags: ['welpen', 'protein', 'wachstum', 'entwicklung', 'verdaulichkeit'],
      topicHub: 'welpen',
      relatedProducts: [],
    },
    {
      slug: 'omega-3-arthrose-2010',
      title: 'Multicenter veterinary practice assessment of the effects of omega-3 fatty acids on osteoarthritis in dogs',
      authors: ['Hansen, B.', 'Carr, A.', 'Gay, J.', 'et al.'],
      year: 2010,
      journal: 'Journal of the American Veterinary Medical Association',
      doi: '10.2460/javma.236.2.186',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/20043800',
      studyDesign: 'Randomized Controlled Trial (Multicenter)',
      population: 'Haushunde mit Arthrose, n=127 (18 Tierarztpraxen)',
      methodology: 'Multizentrische, randomisierte, doppelblinde, kontrollierte Studie über 6 Monate. Hunde erhielten entweder Standardfutter oder Testfutter mit 31-fach erhöhtem Omega-3-Gehalt und 34-fach reduziertem Omega-6:Omega-3-Verhältnis.',
      keyFindings: 'Hunde mit Testfutter hatten signifikant höhere Serum-Omega-3-Konzentration und niedrigere Arachidonsäure. Laut Halter verbesserte sich die Fähigkeit, sich aus der Ruheposition zu erheben und zu spielen, bereits nach 6 Wochen. Gehfähigkeit verbesserte sich nach 12 und 24 Wochen.',
      limitations: 'Keine objektiven Beweglichkeitsmessungen (subjektive Halterbewertung). Keine Langzeitdaten über 24 Monate hinaus.',
      bellaSummary: 'Diese große Multicenter-Studie mit 127 Hunden zeigt: Omega-3 hilft bei Arthrose! Die Hunde mit Omega-3-reichem Futter konnten sich besser erheben und bewegen – bereits nach 6 Wochen! Das Wichtigste: Das Verhältnis von Omega-6 zu Omega-3 ist entscheidend. Geduld: Es braucht 6–8 Wochen bis zur Wirkung.',
      evidenceStrength: 'hoch',
      tags: ['senioren', 'gelenke', 'omega-3', 'arthrose', 'epa', 'dha'],
      topicHub: 'senioren',
      relatedProducts: [],
    },
    {
      slug: 'gut-microbiome-review-2024',
      title: 'Understanding the diversity and roles of the canine gut microbiome',
      authors: ['Kim, H.', 'Chae, Y.', 'Cho, J.H.', 'Song, M.', 'et al.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040654',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467234',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zur Struktur und Funktion des kaninen Darmmikrobioms. Analyse der Zusammensetzung, Einflussfaktoren (Genetik, Diät, Antibiotika, Stress, Umgebung) und Auswirkungen auf Gesundheit.',
      keyFindings: 'Das Darmmikrobiom spielt eine vitale Rolle für Verdauung, Immunantwort, Energiestoffwechsel und sogar Verhalten. Eubiosis fördert Gesundheit, Dysbiosis kann zu Gewichtsschwankungen, Stoffwechselstörungen und Verhaltensänderungen führen. Diät ist ein Hauptfaktor für die Balance des Mikrobioms.',
      limitations: 'Review-Studie basiert auf heterogenen Primärstudien. Kausale Zusammenhänge nicht immer eindeutig.',
      bellaSummary: 'Das Darmmikrobiom ist wie ein zweites Gehirn für deinen Hund! Es beeinflusst Verdauung, Immunsystem und sogar Verhalten. Wichtig: Eine ausgewogene Darmflora (Eubiosis) ist essenziell. Diät ist der wichtigste Faktor – was dein Hund isst, prägt seine Darmbakterien.',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'mikrobiom', 'darm', 'immunsystem'],
      topicHub: 'verdauung',
      relatedProducts: [],
    },
    {
      slug: 'canine-obesity-review-2019',
      title: 'Canine and feline obesity: a review of pathophysiology, epidemiology, and clinical management',
      authors: ['Loftus, J.P.', 'Wakshlag, J.J.'],
      year: 2019,
      journal: 'Journal of the American Veterinary Medical Association',
      doi: '10.2460/javma.253.5.627',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31468856',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zu Pathophysiologie, Epidemiologie und klinischem Management von Adipositas bei Hunden und Katzen. Analyse von Energiestoffwechsel, Hormonregulation, Risikofaktoren und Gewichtsverlust-Protokollen.',
      keyFindings: 'Adipositas-Raten bei Hunden haben pandemische Ausmaße erreicht (30–40 % übergewichtig oder adipös). Assoziiert mit Arthrose, Nierenerkrankungen, Insulinresistenz und Neoplasien. Fettgewebe fungiert als endokrines Organ.',
      limitations: 'Review-Studie. Spezifische Empfehlungen nicht für alle Rassen standardisiert.',
      bellaSummary: 'Übergewicht ist ein riesiges Problem – 30–40 % aller Hunde sind betroffen! Und es ist nicht nur kosmetisch: Übergewicht führt zu Arthrose, Diabetes und verkürzt das Leben. Fettgewebe ist wie ein Hormonorgan – es beeinflusst den ganzen Stoffwechsel. Wenn dein Hund zu dick ist, frag deinen Tierarzt nach einem Plan!',
      evidenceStrength: 'hoch',
      tags: ['uebergewicht', 'adipositas', 'stoffwechsel', 'gesundheit', 'gewichtsverlust'],
      topicHub: 'uebergewicht',
      relatedProducts: [],
    },
    {
      slug: 'probiotics-prebiotics-review-2024',
      title: 'The Function of Probiotics and Prebiotics on Canine Intestinal Health and Their Evaluation Criteria',
      authors: ['Xia, J.', 'Cui, Y.', 'Guo, Y.', 'Liu, Y.', 'Deng, B.', 'Han, S.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040578',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467235',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zur Funktion von Probiotika und Präbiotika für die Darmgesundheit von Hunden. Analyse der Wechselwirkungen mit Darmmikrobiota, epithelialer Barriere-Funktion und Immunfunktion.',
      keyFindings: 'Probiotika und Präbiotika spielen eine Schlüsselrolle bei der Regulation der Darmgesundheit durch Modulation des Mikrobioms, Stärkung der epithelialen Barriere und Verbesserung der Darmimmunität. Einheitliche Evaluationsstandards fehlen aktuell.',
      limitations: 'Review-Studie. Keine standardisierten Evaluationskriterien. Langzeiteffekte nicht vollständig untersucht.',
      bellaSummary: 'Probiotika und Präbiotika können wirklich helfen! Sie stärken die Darmbarriere, modulieren das Mikrobiom und verbessern die Immunfunktion. Nicht alle Produkte sind gleich gut – es fehlen einheitliche Standards. Such nach Produkten mit nachgewiesenen Stämmen.',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'probiotika', 'praebiotika', 'mikrobiom', 'immunsystem'],
      topicHub: 'verdauung',
      relatedProducts: [],
    },
    {
      slug: 'antioxidants-dry-food-2023',
      title: 'Dry food affects the oxidative/antioxidant profile of dogs',
      authors: ['Usuga, A.', 'Rojano, B.A.', 'Duque, J.C.', 'Mesa, C.', 'Restrepo, O.', 'Gomez, L.M.', 'Restrepo, G.'],
      year: 2023,
      journal: 'Animals',
      doi: '10.3390/ani13081327',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/36973234',
      studyDesign: 'Crossover Study',
      population: 'Beagle-Hunde (männlich), n=6',
      methodology: 'Crossover-Studie mit 4 experimentellen Diäten (Trockenfutter A–D). Jedes Futter wurde 5 Wochen gefüttert. Bewertung von Phenolgehalt, antioxidativer Kapazität und oxidativem Stress im Blutplasma.',
      keyFindings: 'Futter A hatte höchste Phenol- und antioxidative Kapazität. Individuelle Hunde zeigten signifikant unterschiedliche Redox-Zustände selbst bei gleichem Futter. Trockenfutter beeinflusst oxidatives/antioxidatives Profil, aber dies scheint unabhängig vom antioxidativen Profil des Futters.',
      limitations: 'Kleine Stichprobe (n=6). Nur männliche Beagle. Kurze Fütterungsperioden (5 Wochen).',
      bellaSummary: 'Trockenfutter beeinflusst den oxidativen Stress bei Hunden – aber nicht immer so wie erwartet! Futter mit hoher antioxidativer Kapazität im Labor führte nicht automatisch zu besseren Blutwerten. Interessant: Jeder Hund reagiert anders auf das gleiche Futter.',
      evidenceStrength: 'mittel',
      tags: ['trockenfutter', 'antioxidantien', 'oxidativer-stress', 'individuelle-variation'],
      topicHub: 'trockenfutter',
      relatedProducts: [],
    },
    {
      slug: 'diabetes-glycemic-response-2023',
      title: 'Effect of diet on postprandial glycemic and insulin responses in healthy dogs',
      authors: ['Vastolo, A.', 'Gizzarelli, M.', 'Ruggiero, A.', 'Alterisio, M.C.', 'Calabrò, S.', 'Ferrara, M.', 'Cutrignelli, M.I.'],
      year: 2023,
      journal: 'Animals',
      doi: '10.3390/ani131012016',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/37867234',
      studyDesign: 'Crossover Study',
      population: 'Gesunde Hunde, n=15',
      methodology: 'Crossover-Studie mit 3 Diäten: zwei getreidefreie (GF1, GF2) und eine getreidebasierte (CB). Jede Diät 50 Tage. Messung von Blutzucker und Insulin vor und nach 120, 240 und 360 Minuten.',
      keyFindings: 'GF1-Diät verursachte kleinste Glukose- und Insulin-AUC und niedrigsten Glukose-Tiefpunkt. Getreidebasierte Diät (CB) hatte höchste Fructosamin-Werte und höchste Glukose-Mittelwerte. Getreidefreies Futter ist nicht automatisch besser.',
      limitations: 'Kleine Stichprobe (n=15). Nur gesunde Hunde. Keine Langzeitbeobachtung.',
      bellaSummary: 'Getreidefreies Futter ist nicht automatisch besser für den Blutzucker! GF1 (getreidefrei) hatte die beste Blutzucker-Kurve, aber GF2 (auch getreidefrei) hatte schlechtere Werte als das getreidebasierte Futter. Die Kohlenhydratquelle und -zusammensetzung sind entscheidend, nicht das "grain-free"-Label.',
      evidenceStrength: 'mittel',
      tags: ['diabetes', 'blutzucker', 'insulin', 'kohlenhydrate', 'getreidefrei'],
      topicHub: 'trockenfutter',
      relatedProducts: [],
    },
    {
      slug: 'fiber-digestibility-age-2024',
      title: 'Evaluation of the nutrient digestibility at each age in dogs diet by in vitro and in vivo methods',
      authors: ['Jeon, K.', 'Lee, J.', 'Song, M.', 'Kim, K.', 'Jo, M.', 'Chang, S.', 'Song, D.', 'Park, S.', 'Kim, H.', 'Cho, J.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040576',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467236',
      studyDesign: 'Comparative Study',
      population: 'Beagle-Hunde, n=18 (6 Welpen, 6 Erwachsene, 6 Senioren)',
      methodology: 'Vergleich von in vitro und in vivo Verdaulichkeit bei Hunden unterschiedlichen Alters. In vitro Methode mit Pepsin und Pankreatin-Inkubation. In vivo Methode mit 18 Beagles in 3 Altersgruppen.',
      keyFindings: 'In vitro Verdaulichkeitswerte waren höher als in vivo Werte. Bei Welpen und Erwachsenen starke Korrelation. Bei Senioren niedrigere Korrelationen (r²=0,18–0,42). In vitro Methode hat Potenzial für Welpen und Erwachsene, nicht für Senioren.',
      limitations: 'Nur eine Rasse (Beagle). Kleine Stichprobe (n=18). In vitro Methode nicht für alle Nährstoffe gleich präzise.',
      bellaSummary: 'Die Verdaulichkeit ändert sich mit dem Alter! Welpen und Erwachsene haben ähnliche Verdaulichkeit, aber Senioren sind anders – Laborwerte stimmen bei ihnen weniger gut mit der Realität überein. Futter für Senioren muss anders formuliert sein als für jüngere Hunde.',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'faser', 'alter', 'verdaulichkeit', 'senioren'],
      topicHub: 'verdauung',
      relatedProducts: [],
    },
    // ── 20 NEUE STUDIEN ────────────────────────────────────────────────────────
    {
      slug: 'hydrolyzed-salmon-poultry-elimination-trial-2025',
      title: 'Evaluation of hydrolyzed salmon and hydrolyzed poultry feather diets in restrictive diet trials for diagnosis of food allergies in pruritic dogs',
      authors: ['Lewis, T.P.', 'Moore, G.E.', 'Laporte, C.', 'Daristotle, L.', 'Frantz, N.Z.'],
      year: 2025,
      journal: 'Frontiers in Veterinary Science',
      doi: '10.3389/fvets.2025.1560806',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/40406274',
      studyDesign: 'RCT',
      population: 'Hunde mit Verdacht auf kutane Futtermittelunverträglichkeit (CAFR), n=57 eingeschlossen, 47 abgeschlossen, 6 private Dermatologiepraxen, USA',
      methodology: 'Multizentrisch, dreifachblind, randomisiert, Crossover-Design. Hunde erhielten abwechselnd hydrolysierte Lachs- (HS) oder hydrolysierte Geflügelfedern-Diät (HPF) für jeweils 8 Wochen. Pruritus und Hautläsionen wurden mit PVAS und CADESI-4 bewertet.',
      keyFindings: 'Beide Diäten reduzierten Pruritus und Dermatitis-Score signifikant, mit vergleichbarer Wirksamkeit und Verträglichkeit. Über 50 % der Hunde mit CAFR benötigten mehr als 4 Wochen für eine relevante Verbesserung.',
      limitations: 'Spezifische Allergene pro Hund unbekannt; möglicher Selektionsbias durch compliance-starke Besitzer; keine Auswaschphase zwischen den Diäten.',
      bellaSummary: 'Wenn dein Hund ständig kratzt und der Tierarzt eine Futtermittelunverträglichkeit vermutet, braucht ihr wirklich Geduld: Diese Studie zeigt, dass mehr als die Hälfte der betroffenen Hunde mindestens 4 Wochen braucht, bis die Eliminationsdiät wirkt. Hydrolysiertes Lachs- oder Geflügelprotein funktioniert dabei gleich gut. Brich die Diät also nicht zu früh ab!',
      evidenceStrength: 'hoch',
      tags: ['eliminationsdiät', 'hydrolysiertes-protein', 'futtermittelallergie', 'pruritus', 'hautgesundheit'],
      topicHub: 'allergien',
      relatedProducts: [],
    },
    {
      slug: 'hydrolyzed-diet-lymphocyte-stimulation-dogs-2020',
      title: 'Hydrolyzed diets may stimulate food-reactive lymphocytes in dogs',
      authors: ['Masuda, K.', 'Sato, A.', 'Tanaka, A.', 'Kumagai, A.'],
      year: 2020,
      journal: 'Journal of Veterinary Medical Science',
      doi: '10.1292/jvms.19-0222',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31875597',
      studyDesign: 'Comparative Study',
      population: '316 Hunde mit Verdacht auf Futtermittelallergien, periphere Blutmonozyten analysiert',
      methodology: 'Zwei kommerzielle hydrolysierte Diäten wurden chemisch mittels Gelelektrophorese analysiert. Immunzellen von Hunden wurden mit Diätextrakten kultiviert und aktivierte T-Helfer-Lymphozyten mittels Durchflusszytometrie quantifiziert.',
      keyFindings: 'Beide hydrolysierten Diäten enthielten Peptide (1,5–3,5 kDa), die bei ca. 24–29 % der Proben T-Helfer-Lymphozyten aktivierten. Bei Hunden, die auf Geflügelantigene reagierten, stieg die Aktivierungsrate auf 30–39 %. Hydrolysierte Diäten sind nicht für alle futtermittelallergischen Hunde geeignet.',
      limitations: 'Laboruntersuchung ohne direkte klinische Endpunkte; In-vitro-Aktivierung entspricht nicht zwingend klinischen Symptomen.',
      bellaSummary: 'Viele Hundebesitzer glauben, dass hydrolysiertes Futter immer sicher ist – aber diese Studie zeigt: Bei fast jedem vierten Hund können selbst stark aufgespaltene Proteine noch Immunreaktionen auslösen. Wenn dein Hund trotz Hydrolysat-Diät weiter kratzt, kann das der Grund sein – sprich mit deinem Tierarzt.',
      evidenceStrength: 'mittel',
      tags: ['hydrolysiertes-protein', 'lymphozyten', 'immunreaktion', 'futtermittelallergie', 'kreuzreaktion'],
      topicHub: 'allergien',
      relatedProducts: [],
    },
    {
      slug: 'common-food-allergens-dogs-review-2016',
      title: 'Critically appraised topic on adverse food reactions of companion animals (2): common food allergen sources in dogs and cats',
      authors: ['Mueller, R.S.', 'Olivry, T.', 'Prélaud, P.'],
      year: 2016,
      journal: 'BMC Veterinary Research',
      doi: '10.1186/s12917-016-0633-8',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/26753610',
      studyDesign: 'Systematic Review',
      population: 'Literaturanalyse zu kutanen Futtermittelunverträglichkeiten (CAFRs) bei Hunden und Katzen',
      methodology: 'Systematische Recherche und kritische Auswertung veröffentlichter Studien zu häufigen Futterallergenen bei Hunden und Katzen. Fokus auf Identifizierung der häufigsten Auslöser.',
      keyFindings: 'Die häufigsten Futterallergene beim Hund sind Rind, Milchprodukte, Huhn und Weizen. Bei Katzen sind es Rind, Fisch und Huhn. Die Autoren empfehlen, Rind und Milchprodukte als erste Provokationsnahrungsmittel zu testen.',
      limitations: 'Review beschränkt auf Literatur bis Mitte Januar 2015; Diagnosemethoden variierten zwischen den analysierten Studien.',
      bellaSummary: 'Welches Futter löst bei Hunden am häufigsten Allergien aus? Laut dieser umfangreichen Auswertung sind es Rind, Milchprodukte, Huhn und Weizen – also ausgerechnet die häufigsten Hauptzutaten in vielen Hundefuttern! Wenn du einen allergieverdächtigen Hund hast, starte beim Tierarzt eine Eliminationsdiät mit exotischem Protein.',
      evidenceStrength: 'hoch',
      tags: ['futtermittelallergie', 'rind', 'huhn', 'weizen', 'eliminationsdiät', 'allergen'],
      topicHub: 'allergien',
      relatedProducts: [],
    },
    {
      slug: 'atopic-dermatitis-omega3-enriched-diet-rct-2021',
      title: 'Randomized, double-blind, placebo-controlled clinical trial measuring the effect of a dietetic food on dermatologic scoring and pruritus in dogs with atopic dermatitis',
      authors: ['Sánchez de Santiago, M.', 'González Arribas, J.L.', 'Moral Llamas, Y.', 'Becvarova, I.', 'Meyer, H.'],
      year: 2021,
      journal: 'BMC Veterinary Research',
      doi: '10.1186/s12917-021-03063-w',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/34798876',
      studyDesign: 'RCT',
      population: '40 Hunde mit atopischer Dermatitis (Alter 1–11 Jahre; Gewicht 1,7–37 kg)',
      methodology: 'Randomisierte, doppelblinde, placebokontrollierte Studie über 60 Tage. Testdiät angereichert mit Omega-3-Fettsäuren, Polyphenolen, Vitamin C und E. Bewertung mit CADESI-4 und Pruritus-Score (0–10).',
      keyFindings: 'Testdiät reduzierte CADESI-4-Score um 48,5 % bis Tag 60 (p=0,0007). Kontrolldiät zeigte keine signifikante Verbesserung der Hautläsionen. Besitzer der Testdiät-Gruppe berichteten 46,4 % weniger Juckreiz (p<0,0001).',
      limitations: 'Beide Gruppen erhielten gleichzeitig Oclacitinib; zusammengesetzte Diäteffekte wurden evaluiert statt individueller Nährstoffe.',
      bellaSummary: 'Omega-3-Fettsäuren, Polyphenole, Vitamin C und E – wenn all das im Futter steckt, kann das den Juckreiz bei Hunden mit Hautallergien fast halbieren! Diese klinische Studie zeigt, dass speziell angereicherte Diäten wirklich helfen können. Wenn dein Hund unter atopischer Dermatitis leidet, lohnt es sich, beim Futter genauer hinzuschauen.',
      evidenceStrength: 'hoch',
      tags: ['allergien', 'atopische-dermatitis', 'omega-3', 'hautgesundheit', 'pruritus', 'juckreiz'],
      topicHub: 'allergien',
      relatedProducts: [],
    },
    {
      slug: 'barf-fecal-microbiome-metabolome-2018',
      title: 'The fecal microbiome and metabolome differs between dogs fed Bones and Raw Food (BARF) diets and dogs fed commercial diets',
      authors: ['Schmidt, M.', 'Unterer, S.', 'Suchodolski, J.S.', 'Honneffer, J.B.', 'Guard, B.C.', 'Lidbury, J.A.', 'Steiner, J.M.', 'Fritz, J.', 'Kölle, P.'],
      year: 2018,
      journal: 'PLOS ONE',
      doi: '10.1371/journal.pone.0201279',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/30110340',
      studyDesign: 'Comparative Study',
      population: '27 BARF-gefütterte Hunde und 19 Hunde auf kommerzieller Diät',
      methodology: '16S-rRNA-Gensequenzierung zur Mikrobiomanalyse, qPCR für spezifische Bakterien, Gaschromatographie-Massenspektrometrie für Metabolomik.',
      keyFindings: 'BARF-Hunde hatten signifikant höhere Protein- und Fettaufnahme bei niedrigerem Kohlenhydrat- und Ballaststoffgehalt. BARF-Hunde zeigten erhöhte Dysbiose-Marker (mehr E. coli, weniger Faecalibacterium) und ein klar abweichendes Metabolom.',
      limitations: 'Variierende Makronährstoffprofile zwischen kommerziellen Diäten; gemischte Rassen; keine Kontrolldiät.',
      bellaSummary: 'BARF-Futter verändert die Darmflora deines Hundes erheblich – und nicht immer zum Guten. Diese Studie fand, dass rohfuttergefütterte Hunde andere (und teils problematischere) Darmbakterien hatten als Hunde mit kommerziellem Futter. Die Auswirkungen auf den Darm sind real und sollten beim Umstieg mitbedacht werden.',
      evidenceStrength: 'mittel',
      tags: ['barf', 'rohfutter', 'mikrobiom', 'metabolom', 'darmgesundheit', 'e-coli'],
      topicHub: 'barf',
      relatedProducts: [],
    },
    {
      slug: 'raw-diet-blood-markers-staffordshire-2020',
      title: 'The effect of a raw vs dry diet on serum biochemical, hematologic, blood iron, B12, and folate levels in Staffordshire Bull Terriers',
      authors: ['Anturaniemi, J.', 'Zaldívar-López, S.', 'Moore, R.', 'Kosola, M.', 'Sankari, S.', 'Barrouin-Melo, S.M.', 'Hielm-Björkman, A.'],
      year: 2020,
      journal: 'Veterinary Clinical Pathology',
      doi: '10.1111/vcp.12852',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/32329096',
      studyDesign: 'Comparative Study',
      population: '33 Staffordshire Bull Terrier (18 mit atopischer Dermatitis, 7 gesunde Kontrollen, 8 Borderline)',
      methodology: 'Vergleich einer wärmeverarbeiteten kohlenhydratreichen Diät vs. einer nicht verarbeiteten fettreichen Rohdiät. Messung hämatologischer Parameter, Serumbiochemie, Folat, B12 und Eisen zu Beginn und nach der Intervention.',
      keyFindings: 'Rohfutter-Hunde hatten höhere Erythrozytenzahlen, aber niedrigere alkalische Phosphatase, Phosphor und Cholesterin. Folat, B12 und Eisen sanken in der Rohfutter-Gruppe signifikant, blieben aber meist im Referenzbereich.',
      limitations: 'Pilotstudie mit kleiner Stichprobe; gemischte Diagnosegruppen; keine randomisierte Zuteilung.',
      bellaSummary: 'Was passiert im Blut, wenn du deinen Hund auf Rohfutter umstellst? Einige Werte verbessern sich, andere – wie Folsäure, B12 und Eisen – gehen runter. Alle blieben im Normbereich, aber das unterstreicht: Rohfütterung muss gut geplant sein und regelmäßige Blutuntersuchungen beim Tierarzt gehören dazu.',
      evidenceStrength: 'niedrig',
      tags: ['barf', 'rohfutter', 'blutbild', 'b12', 'eisen', 'nährstoffversorgung'],
      topicHub: 'barf',
      relatedProducts: [],
    },
    {
      slug: 'dry-wet-food-oral-microbiota-dogs-2022',
      title: 'Oral microbiota populations of adult dogs consuming wet or dry foods',
      authors: ['Oba, P.M.', 'Sieja, K.M.', 'Keating, S.C.J.', 'Hristova, T.', 'Somrak, A.J.', 'Swanson, K.S.'],
      year: 2022,
      journal: 'Journal of Animal Science',
      doi: '10.1093/jas/skac200',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/35641105',
      studyDesign: 'Comparative Study',
      population: '12 adulte weibliche Beagle (Ø 6,0 Jahre, Ø 10,78 kg), kontrollierte Interventionsstudie über 6 Wochen',
      methodology: 'Veterinärzahnärztliche Bewertung von Plaque, Zahnstein, Gingivitis; Atemgeruchmessung; Speichel-pH; Illumina-Sequenzierung der supragingivalen und subgingivalen Plaque.',
      keyFindings: 'Trockenfutter-Hunde zeigten weniger Mundgeruch und geringere Plaquebildung sowie höheren Speichel-pH. Das orale Mikrobiom der Trockenfutter-Gruppe wich stärker in Richtung Parodontalgesundheit ab.',
      limitations: 'Nur eine Rasse (Beagle); kleine Stichprobe (n=12); 6 Wochen möglicherweise zu kurz für Langzeitaussagen.',
      bellaSummary: 'Trockenfutter vs. Nassfutter – was ist besser für die Zähne? Laut dieser Studie schneidet Trockenfutter beim Mundgeruch und bei der Plaquebildung besser ab. Aber: Weder Trocken- noch Nassfutter allein ersetzt regelmäßiges Zähneputzen!',
      evidenceStrength: 'mittel',
      tags: ['trockenfutter', 'nassfutter', 'zahngesundheit', 'mundmikrobiom', 'plaque', 'zahnstein'],
      topicHub: 'trockenfutter',
      relatedProducts: [],
    },
    {
      slug: 'cognitive-dysfunction-mct-diet-senior-dogs-2018',
      title: 'Efficacy of a Therapeutic Diet on Dogs With Signs of Cognitive Dysfunction Syndrome (CDS): A Prospective Double Blinded Placebo Controlled Clinical Study',
      authors: ['Pan, Y.', 'Landsberg, G.', 'Mougeot, I.', 'Kelly, S.', 'Xu, H.', 'Bhatnagar, S.', 'Gardner, C.L.', 'Milgram, N.W.'],
      year: 2018,
      journal: 'Frontiers in Nutrition',
      doi: '10.3389/fnut.2018.00127',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/30619873',
      studyDesign: 'RCT',
      population: '87 Hunde mit CDS-Anzeichen, randomisiert auf drei Diätgruppen (29 pro Gruppe)',
      methodology: 'Prospektive, doppelblinde, placebokontrollierte Studie über 90 Tage. Hunde wurden mithilfe von Verhaltensfragebögen auf CDS gescreent. Neubewertung an Tag 30 und Tag 90 in sechs CDS-Verhaltenskategorien.',
      keyFindings: 'Die 6,5 %-MCT-Diät zeigte signifikante Verbesserungen in allen sechs CDS-Kategorien (p<0,05). Die Kontrollgruppe verbesserte sich nur in vier Kategorien. Die MCT-Diät verbesserte spatiales Lernen, Gedächtnis, Aufmerksamkeit und exekutive Funktionen.',
      limitations: 'Variierende Abbruchraten zwischen Gruppen; Palatabilität der 9 %-MCT-Diät war problematisch.',
      bellaSummary: 'Vergisst dein Senior-Hund bekannte Menschen, ist desorientiert oder wacht nachts ständig auf? Das könnte Canine Cognitive Dysfunction sein – eine Art Alzheimer beim Hund. Diese gut durchgeführte Studie zeigt, dass ein spezielles Futter mit mittelkettigen Fettsäuren (MCTs) das Denken und Verhalten älterer Hunde messbar verbessern kann.',
      evidenceStrength: 'hoch',
      tags: ['senioren', 'kognitive-dysfunktion', 'MCT', 'gehirn', 'gedächtnis', 'CDS'],
      topicHub: 'senioren',
      relatedProducts: [],
    },
    {
      slug: 'omega3-osteoarthritis-systematic-review-2022',
      title: 'A 2022 Systematic Review and Meta-Analysis of Enriched Therapeutic Diets and Nutraceuticals in Canine and Feline Osteoarthritis',
      authors: ['Barbeau-Grégoire, M.', 'Otis, C.', 'Cournoyer, A.', 'Moreau, M.', 'Lussier, B.', 'Troncy, E.'],
      year: 2022,
      journal: 'International Journal of Molecular Sciences',
      doi: '10.3390/ijms231810384',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/36142319',
      studyDesign: 'Systematic Review',
      population: '57 Artikel analysiert; 72 klinische Studien; 38 verschiedene Verbindungen evaluiert',
      methodology: 'Systematischer Review mit Meta-Analyse. Eingeschlossene Studien: klinische Versuche von 1980 bis Oktober 2021. Dreiteiliges Qualitätsbewertungssystem zu Biasrisiko, methodischer Qualität und Beweisqualität.',
      keyFindings: 'Klare klinische analgetische Wirksamkeit für Omega-3-angereicherte Diäten und Omega-3-Supplemente. Ausgeprägte Nicht-Wirksamkeit für Chondroitin-Glucosamin-Produkte.',
      limitations: 'Überwiegend subjektive, nicht validierte Messinstrumente in den Primärstudien; Variabilität in Formulierungen und Dosierungen.',
      bellaSummary: 'Glucosamin und Chondroitin – fast jeder Hundebesitzer kennt diese Mittel gegen Gelenkschmerzen. Aber dieser große Überblick über 57 Studien zeigt: Sie wirken kaum messbar! Was wirklich hilft, sind Omega-3-Fettsäuren. Also lieber zu einem hochwertigen Senior-Futter mit viel Omega-3 greifen!',
      evidenceStrength: 'hoch',
      tags: ['senioren', 'arthrose', 'omega-3', 'gelenke', 'glucosamin', 'entzündung'],
      topicHub: 'senioren',
      relatedProducts: [],
    },
    {
      slug: 'dha-fish-oil-cognitive-puppies-2023',
      title: 'The Supplementation of Docosahexaenoic Acid-Concentrated Fish Oil Enhances Cognitive Function in Puppies',
      authors: ['Rodrigues, R.B.A.', 'Zafalon, R.V.A.', 'Rentas, M.F.', 'et al.'],
      year: 2023,
      journal: 'Animals (Basel)',
      doi: '10.3390/ani13182938',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/37760338',
      studyDesign: 'RCT',
      population: '12 Welpen im Alter von 3 Monaten, blockiert nach Rasse, randomisiert auf zwei Gruppen',
      methodology: 'Kontrollierte Studie über 90 Tage: Kontrollgruppe vs. Experimentalgruppe mit 40 mg DHA/kg Körpergewicht täglich. Kognitive Funktion via Objektdiskriminationstest (normale und reverse Phase).',
      keyFindings: 'DHA-supplementierte Welpen zeigten signifikant höhere Richtigantwortraten im Lerntest. Serum-EPA+DHA-Spiegel stiegen in der Supplementierungsgruppe an und übertrafen die Kontrollgruppe ab Tag 60.',
      limitations: 'Sehr kleine Stichprobe (n=12); kurze Interventionsdauer; begrenzte Übertragbarkeit auf alle Rassen.',
      bellaSummary: 'Du willst, dass dein Welpe schnell lernt und klug wird? Dann sind Omega-3-Fettsäuren, vor allem DHA aus Fischöl, die wichtigsten Nährstoffe fürs Gehirn. Diese Studie zeigt, dass DHA-supplementierte Welpen im Lerntest deutlich besser abschnitten. Gutes Welpenfutter sollte immer DHA und EPA enthalten!',
      evidenceStrength: 'mittel',
      tags: ['welpen', 'DHA', 'EPA', 'omega-3', 'gehirnentwicklung', 'lernen', 'kognition'],
      topicHub: 'welpen',
      relatedProducts: [],
    },
    {
      slug: 'calcium-phosphorus-puppy-requirements-2019',
      title: 'Factorial calculation of calcium and phosphorus requirements of growing dogs',
      authors: ['Böswald, L.F.', 'Klein, C.', 'Dobenecker, B.', 'Kienzle, E.'],
      year: 2019,
      journal: 'PLOS ONE',
      doi: '10.1371/journal.pone.0220305',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31374084',
      studyDesign: 'Comparative Study',
      population: 'Modellierte Welpen verschiedener Gewichtsklassen (5, 10, 20, 35, 60 kg Erwachsenengewicht) über 11 Entwicklungsphasen (9–52 Wochen)',
      methodology: 'Vergleich zweier Berechnungsmethoden für den Mineralbedarf: NRC-Extrapolation vs. faktorieller Berechnung (unter Berücksichtigung endogener Verluste, Gewebemineralisierung und Bioverfügbarkeit).',
      keyFindings: 'Die NRC-Extrapolationsmethode überschätzt den Calciumbedarf bei kleineren Rassen und älteren Welpen um bis zu 60 %. Vor allem Großrasseiwelpen benötigen sehr präzise Kalziumversorgung.',
      limitations: 'Analyse basiert auf modellierten, nicht real gefütterten Welpen; tatsächliche metabolische Auswirkungen nicht empirisch überprüft.',
      bellaSummary: 'Calcium ist super wichtig für Welpen – aber zu viel davon schadet genauso wie zu wenig! Diese Studie zeigt, dass die Empfehlungen für große Hunderassen oft überschätzt werden. Gerade bei Großrasseiwelpen kann zu viel Calcium zu Skeletterkrankungen führen. Deshalb ist es so wichtig, ein Welpenfutter zu kaufen, das speziell für die Rassegroße deines Hundes entwickelt wurde.',
      evidenceStrength: 'mittel',
      tags: ['welpen', 'calcium', 'phosphor', 'skelettentwicklung', 'großrassen', 'wachstum', 'mineralstoffe'],
      topicHub: 'welpen',
      relatedProducts: [],
    },
    {
      slug: 'caloric-restriction-weight-loss-dogs-rct-2019',
      title: 'An open-label randomised clinical trial to compare the efficacy of dietary caloric restriction and physical activity for weight loss in overweight pet dogs',
      authors: ['Chapman, M.', 'Woods, G.R.T.', 'Ladha, C.', 'Westgarth, C.', 'German, A.J.'],
      year: 2019,
      journal: 'Veterinary Journal',
      doi: '10.1016/j.tvjl.2018.11.013',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/30606441',
      studyDesign: 'RCT',
      population: '13 übergewichtige Hunde mit einem Body-Condition-Score von 6–9/9',
      methodology: 'Randomisierte klinische Studie: Kalorienrestriktion (therapeutische Gewichtsreduktionsdiät) vs. gesteigerter körperlicher Aktivität (≥33 % mehr Bewegung). Messung von Körpergewicht, Körperumfängen und körperlicher Aktivität via triaxialem Beschleunigungsmesser.',
      keyFindings: 'Diätetische Kalorienrestriktion führte zu signifikantem Gewichtsverlust (−10 % Startgewicht). Die Aktivitätsgruppe zeigte keinen signifikanten Gewichtsverlust (−2 %).',
      limitations: 'Sehr kleine Stichprobe (n=13); offenes Design ohne Verblindung; kurze Beobachtungszeit.',
      bellaSummary: 'Dein Hund ist zu dick und mehr Spazierengehen reicht nicht? Diese Studie hat das wissenschaftlich belegt: Allein mehr Bewegung hat beim Hundegewicht kaum geholfen – erst die Futterreduktion brachte echte Ergebnisse. Wenn dein Hund abnehmen muss, ist Futtermengenmanagement der Schlüssel!',
      evidenceStrength: 'mittel',
      tags: ['übergewicht', 'gewichtsmanagement', 'kalorienrestriktion', 'diätfutter', 'bewegung'],
      topicHub: 'uebergewicht',
      relatedProducts: [],
    },
    {
      slug: 'weight-loss-high-protein-fiber-microbiome-2022',
      title: 'Weight loss and high-protein, high-fiber diet consumption impact blood metabolite profiles, body composition, fecal microbiota, and fecal metabolites of adult dogs',
      authors: ['Phungviwatnikul, T.', 'Lee, A.H.', 'Belchik, S.E.', 'Suchodolski, J.S.', 'Swanson, K.S.'],
      year: 2022,
      journal: 'Journal of Animal Science',
      doi: '10.1093/jas/skab379',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/34967874',
      studyDesign: 'Kohortenstudie',
      population: '12 kastrierte weibliche adulte Hunde (Ø 5,5 Jahre; Ø 14,8 kg Startgewicht), prospektive 24-Wochen-Interventionsstudie',
      methodology: '4-wöchige Baseline-Phase mit Hochprotein-Hochballaststoff-Erhaltungsfutter, dann 24-wöchige Kalorienrestriktion (Ziel: 1,5 % Gewichtsverlust/Woche). Körperzusammensetzung via DEXA, Blutmetabolite, Aktivität, Darmmikrobiom analysiert.',
      keyFindings: 'Hunde erzielten 31,2 % Gewichtsverlust bei minimalem Verlust an Magermasse. Triglyzeride, Leptin, Insulin, CRP und IL-6 sanken signifikant. Im Mikrobiom nahmen Bifidobacterium und andere nützliche Bakterien zu.',
      limitations: 'Kleine Stichprobe (n=12); nur weibliche Hunde; kurzfristiges Follow-up; nur ein Futtertyp evaluiert.',
      bellaSummary: 'Wenn dein Hund abnimmt, passiert mehr als nur Gewichtsverlust: Diese Studie zeigt, dass übergewichtige Hunde durch eine eiweißreiche, ballaststoffreiche Diät nicht nur schlanker wurden, sondern auch weniger Entzündungsmarker im Blut hatten und eine gesündere Darmflora entwickelten. Abnehmen ist eine echte Rundum-Kur für deinen Hund!',
      evidenceStrength: 'mittel',
      tags: ['übergewicht', 'gewichtsmanagement', 'mikrobiom', 'entzündungsmarker', 'hochprotein', 'ballaststoffe'],
      topicHub: 'uebergewicht',
      relatedProducts: [],
    },
    {
      slug: 'prebiotic-fos-inulin-microbiota-dogs-2017',
      title: 'Molecular assessment of the fecal microbiota in healthy cats and dogs before and during supplementation with fructo-oligosaccharides (FOS) and inulin',
      authors: ['Garcia-Mazcorro, J.F.', 'Barcenas-Walls, J.R.', 'Suchodolski, J.S.', 'Steiner, J.M.'],
      year: 2017,
      journal: 'PeerJ',
      doi: '10.7717/peerj.3184',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/28439463',
      studyDesign: 'Crossover',
      population: 'Zwei aufeinanderfolgende Versuche: Trial 1: 10 Katzen und 10 Hunde; Trial 2: 10 Hunde',
      methodology: '16S-rRNA-Genprofilierung via 454-Pyrosequenzierung; lineare Diskriminanzanalyse (LEfSe) zur Identifizierung responsiver Bakterientaxa; UniFrac-Distanzmetriken.',
      keyFindings: 'Niedrige Prebiotik-Dosis zeigte minimale Mikrobiomveränderungen. Höhere Dosis erhöhte Veillonellaceae und Megamonas bei Hunden – aber die Unterschiede reichten nicht aus, um Bakteriengemeinschaften klar zu trennen.',
      limitations: 'Diverse Tierpopulation; keine standardisierten Fütterungsprotokolle; kommerzielle Formulierung enthielt mehrere Ingredienzien.',
      bellaSummary: 'Präbiotika wie FOS und Inulin gelten als Superfood für die Darmflora – aber diese Studie zeigt: Die Dosis macht den Unterschied! Kleine Mengen veränderten kaum etwas, erst höhere Dosierungen brachten messbare Effekte. Wenn du Präbiotika für deinen Hund kaufst, lohnt es sich, auf die tatsächliche Wirkkonzentration zu achten.',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'präbiotika', 'FOS', 'inulin', 'darmflora', 'mikrobiom', 'ballaststoffe'],
      topicHub: 'verdauung',
      relatedProducts: [],
    },
    {
      slug: 'environmental-impact-dog-cat-diets-2022',
      title: 'Environmental impact of diets for dogs and cats',
      authors: ['Pedrinelli, V.', 'Teixeira, F.A.', 'Queiroz, M.R.', 'Brunetto, M.A.'],
      year: 2022,
      journal: 'Scientific Reports',
      doi: '10.1038/s41598-022-22631-0',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/36396966',
      studyDesign: 'Comparative Study',
      population: '938 Heimtierdiäten analysiert (618 für Hunde, 320 für Katzen); 212 Zutaten ausgewertet',
      methodology: 'Vergleichende Umweltfolgenanalyse für vier Diätkategorien anhand von sechs Umweltmetriken pro 1.000 kcal: Treibhausgasemissionen, Landnutzung, Versauerung, Eutrophierung, Süßwasserverbrauch.',
      keyFindings: 'Nassdiäten hatten den höchsten Umwelteinfluss in allen Kategorien. Trockenfutter verursachte die geringste Umweltbelastung. Es bestand eine positive Korrelation zwischen dem Anteil tierischer Energie und dem Umwelteinfluss.',
      limitations: 'Daten basieren auf dem brasilianischen Markt; Ergebnisse könnten sich regional durch unterschiedliche Produktionsbedingungen unterscheiden.',
      bellaSummary: 'Wusstest du, dass Nassfutter für deinen Hund deutlich mehr Umwelt kostet als Trockenfutter? Diese große Analyse von fast 1.000 Heimtierdiäten zeigte: Je mehr tierische Zutaten im Futter stecken, desto größer der CO₂-Fußabdruck. Ein guter Grund, beim Kauf auch mal auf den Herstellungsprozess zu schauen.',
      evidenceStrength: 'hoch',
      tags: ['nachhaltigkeit', 'co2-fussabdruck', 'umwelteinfluss', 'trockenfutter', 'nassfutter'],
      topicHub: 'nachhaltigkeit',
      relatedProducts: [],
    },
    {
      slug: 'insect-protein-digestibility-dogs-hermetia-2021',
      title: 'Insect Larvae Meal (Hermetia illucens) as a Sustainable Protein Source of Canine Food and Its Impacts on Nutrient Digestibility and Fecal Quality',
      authors: ['Abd El-Wahab, A.', 'Meyer, L.', 'Kölln, M.', 'Chuppava, B.', 'Wilke, V.', 'Visscher, C.', 'Kamphues, J.'],
      year: 2021,
      journal: 'Animals (Basel)',
      doi: '10.3390/ani11092525',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/34573490',
      studyDesign: 'Crossover',
      population: '6 Beagle-Hunde (Ø Körpergewicht 9,64 kg), Crossover-Experiment mit zwei Diätinterventionen',
      methodology: 'Hunde konsumierten abwechselnd Diäten mit Schwarze-Soldatenfliegen-Larvenmehl (BSFL) oder Geflügelmehl (PM), die ca. 30 % der Trockenmasse der Basisdiät ersetzten. Gemessen wurden Verdaulichkeit von Protein und Fett sowie Kotqualität.',
      keyFindings: 'BSFL-basierte Diäten zeigten höhere apparente Proteinverdaulichkeit (82,3 % vs. 80,5 %) und höhere Fettverdaulichkeit (94,5 % vs. 91,6 %) gegenüber Geflügelmehl. Die Kotqualität blieb in beiden Gruppen akzeptabel.',
      limitations: 'Sehr kleine Stichprobe (n=6); nur eine Hunderasse; kurze Studiendauer; keine Langzeit-Gesundheitseffekte untersucht.',
      bellaSummary: 'Insektenprotein aus der Schwarzen Soldatenfliege klingt erstmal gewöhnungsbedürftig – aber für deinen Hund macht das ernährungsphysiologisch richtig Sinn! Diese Studie zeigte, dass Hunde Insektenprotein sogar etwas besser verdauen als herkömmliches Geflügelmehl. Insektenfutter ist also nicht nur nachhaltig – es ist auch gut für den Hundedarm.',
      evidenceStrength: 'mittel',
      tags: ['nachhaltigkeit', 'insektenprotein', 'hermetia-illucens', 'verdaulichkeit', 'alternatives-protein'],
      topicHub: 'nachhaltigkeit',
      relatedProducts: [],
    },
  ]

  const insertedStudies = await db.insert(studies).values(studyData).returning()
  console.log(`✅ ${insertedStudies.length} Studien erstellt`)

  // ── Glossar ─────────────────────────────────────────────────────────────────
  const glossaryData = [
    { slug: 'rct', term: 'RCT (Randomized Controlled Trial)', definition: 'Eine randomisierte kontrollierte Studie ist der Goldstandard der klinischen Forschung. Teilnehmer werden zufällig verschiedenen Gruppen zugeteilt, um Verzerrungen zu minimieren.', explanation: 'Stell dir vor: Eine Gruppe bekommt Futter A, die andere Futter B – aber wer was bekommt, wird per Zufall entschieden. So stellt man sicher, dass das Ergebnis wirklich durch das Futter und nicht durch andere Faktoren zustande kommt.', category: 'Methodik' },
    { slug: 'meta-analyse', term: 'Meta-Analyse', definition: 'Eine statistische Methode, die Ergebnisse mehrerer unabhängiger Studien zu einem Thema zusammenfasst und analysiert, um zu einer Gesamtaussage zu kommen.', explanation: 'Statt nur eine Studie zu lesen, schaut man sich alle Studien zu einem Thema an und rechnet die Ergebnisse zusammen. Das ist aussagekräftiger als einzelne Studien.', category: 'Methodik' },
    { slug: 'mikrobiom', term: 'Mikrobiom', definition: 'Die Gesamtheit aller Mikroorganismen (Bakterien, Viren, Pilze) in einem bestimmten Lebensraum, insbesondere im Darm. Das Darmmikrobiom spielt eine wichtige Rolle für Verdauung und Immunsystem.', explanation: 'Der Darm ist wie ein kleiner Kosmos aus Milliarden Bakterien. Diese helfen bei der Verdauung, stärken das Immunsystem und können sogar das Verhalten beeinflussen.', category: 'Gesundheit' },
    { slug: 'dha', term: 'DHA (Docosahexaensäure)', definition: 'Eine Omega-3-Fettsäure, die wichtig für Gehirnentwicklung, Sehkraft und Entzündungshemmung ist. Sie kommt vor allem in Fischöl und bestimmten Algen vor.', explanation: 'DHA ist wie "Superfood" für das Gehirn – besonders wichtig für Welpen und ältere Hunde. Es hilft bei der Gehirnentwicklung und kann Gelenkentzündungen lindern.', category: 'Ernährung' },
    { slug: 'epa', term: 'EPA (Eicosapentaensäure)', definition: 'Eine Omega-3-Fettsäure mit entzündungshemmenden Eigenschaften. Wird oft bei Gelenkproblemen und Hauterkrankungen eingesetzt.', explanation: 'EPA wirkt wie ein natürlicher Entzündungshemmer. Es kann helfen, Gelenkschmerzen zu lindern und die Hautgesundheit zu verbessern.', category: 'Ernährung' },
    { slug: 'aafco', term: 'AAFCO (Association of American Feed Control Officials)', definition: 'US-amerikanische Organisation, die Richtlinien für die Nährstoffzusammensetzung von Tiernahrung festlegt. "AAFCO-zertifiziert" bedeutet, dass ein Futter bestimmte Mindeststandards erfüllt.', explanation: 'AAFCO ist wie eine Qualitätskontrolle für Futter. Wenn ein Futter AAFCO-zertifiziert ist, enthält es alle wichtigen Nährstoffe in der richtigen Menge.', category: 'Standards' },
    { slug: 'fediaf', term: 'FEDIAF (European Pet Food Industry Federation)', definition: 'Europäischer Verband der Tiernahrungsindustrie. Legt Richtlinien für die Nährstoffzusammensetzung von Tiernahrung in Europa fest.', explanation: 'FEDIAF ist die europäische Version von AAFCO. Sie legt fest, was europäisches Hundefutter enthalten muss, um als "vollwertig" zu gelten.', category: 'Standards' },
    { slug: 'oxidativer-stress', term: 'Oxidativer Stress', definition: 'Ein Ungleichgewicht zwischen freien Radikalen und Antioxidantien im Körper. Kann zu Zellschäden führen und wird mit Alterungsprozessen und verschiedenen Krankheiten in Verbindung gebracht.', explanation: 'Stell dir vor, dein Körper ist wie ein Auto – freie Radikale sind wie Rost, Antioxidantien wie Rostschutz. Antioxidantien im Futter können helfen, das zu verhindern.', category: 'Gesundheit' },
    { slug: 'praebiotika', term: 'Präbiotika', definition: 'Unverdauliche Nahrungsbestandteile (meist Ballaststoffe), die das Wachstum nützlicher Darmbakterien fördern.', explanation: 'Präbiotika sind wie Dünger für die guten Darmbakterien. Sie helfen diesen Bakterien, sich zu vermehren und gesund zu bleiben.', category: 'Ernährung' },
    { slug: 'probiotika', term: 'Probiotika', definition: 'Lebende Mikroorganismen, die bei Einnahme in ausreichender Menge gesundheitliche Vorteile bieten. Sie sind die "guten" Bakterien selbst.', explanation: 'Probiotika sind wie eine Armee guter Bakterien, die man zur Verstärkung schickt. Sie können helfen, das Gleichgewicht im Darm wiederherzustellen – besonders nach Antibiotika.', category: 'Ernährung' },
    { slug: 'hydrolysiertes-protein', term: 'Hydrolysiertes Protein', definition: 'Protein, das in kleinere Bestandteile (Peptide und Aminosäuren) zerlegt wurde. Dadurch wird es für das Immunsystem weniger erkennbar und kann bei Allergien besser vertragen werden.', explanation: 'Stell dir vor, ein Protein ist wie ein Lego-Bauwerk – hydrolysiert bedeutet, man hat es in einzelne Steine zerlegt. Das Immunsystem erkennt die einzelnen Steine nicht mehr als "Feind".', category: 'Ernährung' },
    { slug: 'eliminationsdiat', term: 'Eliminationsdiät', definition: 'Eine Diät zur Diagnose von Futterallergien, bei der der Hund nur eine einzige Protein- und Kohlenhydratquelle erhält, die er vorher noch nie gefressen hat.', explanation: 'Um herauszufinden, worauf ein Hund allergisch reagiert, gibt man ihm nur ein Futter mit Zutaten, die er noch nie kannte. Wenn die Symptome verschwinden, hat man den Übeltäter gefunden.', category: 'Methodik' },
    { slug: 'eubiosis', term: 'Eubiosis', definition: 'Ein ausgeglichenes, gesundes Darmmikrobiom. Eubiosis fördert Gesundheit und Stoffwechsel.', explanation: 'Eubiosis ist wie ein perfektes Ökosystem im Darm – alle Bakterien arbeiten harmonisch zusammen. Ideal für Verdauung und Immunsystem.', category: 'Gesundheit' },
    { slug: 'dysbiosis', term: 'Dysbiosis', definition: 'Ein Ungleichgewicht im Darmmikrobiom, bei dem schädliche Bakterien überhandnehmen. Kann zu Verdauungsproblemen, Entzündungen und anderen Gesundheitsproblemen führen.', explanation: 'Dysbiosis ist wie ein Ökosystem aus dem Gleichgewicht – schlechte Bakterien vermehren sich zu sehr. Das kann zu Durchfall, Blähungen und sogar Verhaltensänderungen führen.', category: 'Gesundheit' },
    { slug: 'k9pbn', term: 'K9PBN (Canine Plant-Based Nutrition)', definition: 'Vollwertige, ausgewogene pflanzliche Ernährung für Hunde. Erfordert sorgfältige Supplementierung mit Taurin, L-Carnitin und B-Vitaminen.', explanation: 'K9PBN ist der wissenschaftliche Begriff für pflanzliches Hundefutter, das alle Nährstoffe enthält, die Hunde brauchen. Wichtig: Es muss "complete and balanced" sein.', category: 'Ernährung' },
    { slug: 'rmbd', term: 'RMBD (Raw Meat-Based Diet)', definition: 'Rohfutter-Diät mit rohem Fleisch und tierischen Nebenprodukten. Kann kommerziell oder selbst zubereitet sein. Bringt mikrobiologische Risiken mit sich.', explanation: 'RMBD ist der wissenschaftliche Begriff für BARF und andere Rohfutter-Diäten. Rohfutter kann gesund sein, hat aber echte Risiken – Hygiene ist extrem wichtig!', category: 'Ernährung' },
    { slug: 'arachidonsaeure', term: 'Arachidonsäure', definition: 'Eine Omega-6-Fettsäure, die an Entzündungsreaktionen beteiligt ist. Ein hohes Verhältnis von Omega-6 zu Omega-3 kann Entzündungen fördern.', explanation: 'Arachidonsäure ist wie ein "Entzündungs-Auslöser" im Körper. Das Verhältnis zu Omega-3 ist wichtig – zu viel Omega-6 kann Entzündungen fördern, Omega-3 wirkt dagegen.', category: 'Ernährung' },
    { slug: 'fructosamin', term: 'Fructosamin', definition: 'Ein Blutzucker-Marker, der den durchschnittlichen Blutzuckerspiegel der letzten 1–3 Wochen widerspiegelt. Wird zur Diabetes-Diagnose und -überwachung verwendet.', explanation: 'Fructosamin ist wie ein "Blutzucker-Gedächtnis" – es zeigt, wie der Blutzucker in den letzten Wochen war. Hohe Werte können auf schlecht kontrollierten Diabetes hindeuten.', category: 'Gesundheit' },
    { slug: 'verdaulichkeit', term: 'Verdaulichkeit', definition: 'Der Anteil der Nährstoffe, die vom Körper aufgenommen und verwertet werden können. Unterscheidet sich zwischen Nährstoffen und Altersgruppen.', explanation: 'Verdaulichkeit ist wie die "Effizienz" der Verdauung – wie viel von dem, was der Hund isst, landet tatsächlich im Körper? Senioren haben eine andere Verdaulichkeit als jüngere Hunde.', category: 'Ernährung' },
    { slug: 'in-vitro', term: 'In vitro', definition: 'Laboruntersuchungen außerhalb eines lebenden Organismus, z.B. in Reagenzgläsern. Wird zur Simulation von Verdauungsprozessen verwendet.', explanation: 'In vitro bedeutet "im Glas" – Labor-Tests ohne lebende Tiere. In vitro Tests funktionieren gut für Welpen und Erwachsene, aber weniger gut für Senioren.', category: 'Methodik' },
    { slug: 'in-vivo', term: 'In vivo', definition: 'Untersuchungen an lebenden Organismen. Gibt realistischere Ergebnisse als in vitro, ist aber aufwendiger und ethisch komplexer.', explanation: 'In vivo bedeutet "am lebenden Organismus" – echte Tests mit Hunden. Für die Futterentwicklung sind beide Methoden wichtig – in vitro zum Screening, in vivo zur Bestätigung.', category: 'Methodik' },
    { slug: 'cafr', term: 'CAFR (Cutaneous Adverse Food Reaction)', definition: 'Kutane Futtermittelunverträglichkeit – Hautreaktionen, die durch bestimmte Nahrungsbestandteile ausgelöst werden.', explanation: 'CAFR ist der medizinische Begriff für das, was die meisten Hundebesitzer als "Futterallergie" kennen. Nicht immer steckt eine echte Allergie dahinter – manchmal ist es auch eine Intoleranz.', category: 'Gesundheit' },
    { slug: 'cds', term: 'CDS (Canine Cognitive Dysfunction Syndrome)', definition: 'Eine altersbedingte neurodegenerative Erkrankung bei Hunden, vergleichbar mit Alzheimer beim Menschen. Führt zu Orientierungslosigkeit, Schlafproblemen und Verhaltensveränderungen.', explanation: 'CDS ist wie Alzheimer beim Hund – das Gehirn altert und baut ab. Symptome sind Desorientierung, Schlafstörungen oder verändertes Sozialverhalten. Bestimmte Futter können helfen, den Prozess zu verlangsamen.', category: 'Gesundheit' },
    { slug: 'mct', term: 'MCT (mittelkettige Triglyzeride)', definition: 'Eine Fettform, die das Gehirn als alternative Energiequelle nutzen kann. Wird bei kognitiver Dysfunktion bei Senioren eingesetzt.', explanation: 'MCTs sind wie "Turbokerosin" für das alternde Gehirn. Da ein alterndes Gehirn Glukose schlechter verwerten kann, bieten MCTs eine alternative Energiequelle – und können das Denken verbessern.', category: 'Ernährung' },
  ]

  const insertedGlossary = await db.insert(glossaryTerms).values(glossaryData).returning()
  console.log(`✅ ${insertedGlossary.length} Glossar-Begriffe erstellt`)

  console.log('🎉 Wissensuniversum erfolgreich geseedet!')
  console.log(`   ${hubs.length} Themen-Hubs | ${insertedStudies.length} Studien | ${insertedGlossary.length} Glossar-Einträge`)
}

seedStudies().catch(console.error)
