// 🐕 BELLA — Hunderassen-Seed-Daten
// 50 Rassen mit Profilen für /rasse/[slug] Programmatic SEO
// Ausführen: cd bella-app && pnpm tsx scripts/seed-breeds.ts

import 'dotenv/config'
import { db } from '../src/db'
import { dogBreeds } from '../src/db/schema'

const breeds = [
  {
    slug: 'labrador-retriever',
    name: 'Labrador Retriever',
    alternativeNames: ['Labrador', 'Lab'],
    size: 'gross',
    weightMin: '25',
    weightMax: '36',
    lifeExpectancy: 12,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Übergewicht', 'Ellenbogendysplasie', 'Augenprobleme'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Labradore neigen zu Übergewicht. Strikte Portionskontrolle, gelenkschonende Futter mit Glucosamin/Chondroitin empfohlen. Tagesmenge: 350-500g Trockenfutter, aufgeteilt auf 2 Mahlzeiten.',
    description: 'Der Labrador Retriever ist Deutschlands beliebteste Hunderasse. Freundlich, intelligent und arbeitsfreudig – aber leider auch mit Hang zur Verfressenheit. Beim Futter ist Qualität wichtiger als Menge.',
    imageUrl: '/breeds/labrador-retriever.webp',
  },
  {
    slug: 'golden-retriever',
    name: 'Golden Retriever',
    alternativeNames: ['Goldie'],
    size: 'gross',
    weightMin: '25',
    weightMax: '34',
    lifeExpectancy: 12,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Hautallergien', 'Herzerkrankungen', 'Krebsdisposition'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Goldies brauchen hochwertiges Futter mit Omega-3 für Fell und Haut. Bei Allergien Monoprotein-Futter wählen.',
    description: 'Sanft, kinderlieb, anhänglich – der Golden Retriever ist ein Familienliebling. Häufige Hautprobleme und Allergien machen die Futterwahl besonders wichtig.',
    imageUrl: '/breeds/golden-retriever.webp',
  },
  {
    slug: 'franzoesische-bulldogge',
    name: 'Französische Bulldogge',
    alternativeNames: ['Frenchie', 'Bouledogue Français'],
    size: 'klein',
    weightMin: '8',
    weightMax: '14',
    lifeExpectancy: 11,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Atemprobleme (Brachycephalie)', 'Hautfaltenentzündung', 'Allergien', 'Wirbelsäulenprobleme'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 12,
    feedingNotes: 'Frenchies haben oft empfindliche Mägen. Leicht verdauliches Futter, kleine Portionen, ggf. Anti-Schling-Napf. Bei Allergien Hypoallergen-Futter.',
    description: 'Die Französische Bulldogge ist charmant, verschmust und ein wahrer Wohnungshund. Die Kehrseite: Häufige Atem- und Hautprobleme erfordern angepasste Ernährung.',
    imageUrl: '/breeds/franzoesische-bulldogge.webp',
  },
  {
    slug: 'deutscher-schaeferhund',
    name: 'Deutscher Schäferhund',
    alternativeNames: ['DSH', 'GSD', 'German Shepherd'],
    size: 'gross',
    weightMin: '22',
    weightMax: '40',
    lifeExpectancy: 11,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Hüftdysplasie', 'Magendrehung', 'Degenerative Myelopathie', 'Magen-Darm-Probleme'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Schäferhunde brauchen viel Energie. 2-3 kleine Mahlzeiten täglich (Magendrehung-Risiko!). Auf erhöhtem Magen füttern lassen, nach dem Fressen Ruhe.',
    description: 'Der Deutsche Schäferhund ist arbeitsfreudig, loyal und hochintelligent. Anspruchsvolle Rasse mit speziellen Gesundheitsanfälligkeiten – die richtige Ernährung kann viel bewirken.',
    imageUrl: '/breeds/deutscher-schaeferhund.webp',
  },
  {
    slug: 'jack-russell-terrier',
    name: 'Jack Russell Terrier',
    alternativeNames: ['JRT'],
    size: 'klein',
    weightMin: '5',
    weightMax: '8',
    lifeExpectancy: 14,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Patellaluxation', 'Augenprobleme', 'Taubheit', 'Hüftdysplasie'],
    recommendedProteinPercentage: 28,
    recommendedFatPercentage: 15,
    feedingNotes: 'JRTs verbrennen viel Energie. Hochkalorisches Futter, kleine Pellets. Tagesmenge: 80-120g Trockenfutter.',
    description: 'Kleine Größe, riesige Persönlichkeit. Der Jack Russell ist ein Energiebündel – das Futter muss diesem Lebensstil gerecht werden.',
    imageUrl: '/breeds/jack-russell-terrier.webp',
  },
  {
    slug: 'chihuahua',
    name: 'Chihuahua',
    alternativeNames: ['Chi'],
    size: 'klein',
    weightMin: '1.5',
    weightMax: '3',
    lifeExpectancy: 16,
    activityLevel: 'mittel',
    commonHealthIssues: ['Zahnprobleme', 'Hypoglykämie', 'Patellaluxation', 'Hydrocephalus'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Mini-Pellets für kleines Maul. 3-4 kleine Mahlzeiten täglich (Unterzuckerungsrisiko). Tagesmenge: 30-50g.',
    description: 'Der kleinste Hund der Welt ist temperamentvoll und liebevoll. Wegen der Mini-Statur sind regelmäßige kleine Mahlzeiten Pflicht.',
    imageUrl: '/breeds/chihuahua.webp',
  },
  {
    slug: 'beagle',
    name: 'Beagle',
    alternativeNames: [],
    size: 'mittel',
    weightMin: '9',
    weightMax: '15',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Übergewicht', 'Ohrenentzündungen', 'Epilepsie', 'Bandscheibenprobleme'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 12,
    feedingNotes: 'Beagles fressen ALLES und neigen extrem zu Übergewicht. Strikte Portionskontrolle, Light-Futter bei Tendenz zu Pfunden.',
    description: 'Freundlich, gesellig, dauerhaft hungrig. Beim Beagle ist Disziplin bei der Fütterung entscheidend für ein langes, gesundes Leben.',
    imageUrl: '/breeds/beagle.webp',
  },
  {
    slug: 'mops',
    name: 'Mops',
    alternativeNames: ['Pug'],
    size: 'klein',
    weightMin: '6',
    weightMax: '9',
    lifeExpectancy: 12,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Brachycephales Syndrom', 'Übergewicht', 'Augenprobleme', 'Hüftdysplasie'],
    recommendedProteinPercentage: 24,
    recommendedFatPercentage: 11,
    feedingNotes: 'Möpse neigen zu Übergewicht. Reduzierte Kalorien, hochwertige Proteine. Wegen Brachycephalie: Wassernapf erhöht aufstellen.',
    description: 'Der Mops ist verschmust und gemütlich. Wegen der Kurzschnauze und Tendenz zu Übergewicht braucht er besondere Aufmerksamkeit beim Futter.',
    imageUrl: '/breeds/mops.webp',
  },
  {
    slug: 'dackel',
    name: 'Dackel',
    alternativeNames: ['Teckel', 'Dachshund'],
    size: 'klein',
    weightMin: '7',
    weightMax: '11',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Bandscheibenvorfall', 'Übergewicht', 'Patellaluxation', 'Cushing'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 12,
    feedingNotes: 'Dackel sind besonders rückenanfällig – Übergewicht muss VERMIEDEN werden. Light-Futter, kleine Portionen.',
    description: 'Der Dackel ist mutig, ausdauernd und stur. Sein langer Rücken erfordert ein optimales Gewicht – die Ernährung ist hier Gesundheitsvorsorge.',
    imageUrl: '/breeds/dackel.webp',
  },
  {
    slug: 'border-collie',
    name: 'Border Collie',
    alternativeNames: [],
    size: 'mittel',
    weightMin: '12',
    weightMax: '20',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme (CEA)', 'Epilepsie', 'MDR1-Defekt'],
    recommendedProteinPercentage: 28,
    recommendedFatPercentage: 15,
    feedingNotes: 'Hochaktive Rasse, braucht energiereiches Futter. Bei MDR1-Defekt bestimmte Wirkstoffe vermeiden – im Zweifel Tierarzt fragen.',
    description: 'Wahrscheinlich der intelligenteste Hund der Welt. Border Collies brauchen körperliche UND geistige Auslastung – und Energie aus hochwertigem Futter.',
    imageUrl: '/breeds/border-collie.webp',
  },
  {
    slug: 'australian-shepherd',
    name: 'Australian Shepherd',
    alternativeNames: ['Aussie'],
    size: 'mittel',
    weightMin: '16',
    weightMax: '32',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['MDR1-Defekt', 'Hüftdysplasie', 'Augenprobleme (CEA)', 'Epilepsie'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Aussies brauchen viel Bewegung und entsprechend energiereiches Futter. Bei MDR1-Defekt Hersteller-Liste beachten.',
    description: 'Aussies sind temperamentvoll, klug und arbeitsfreudig. Für die richtige Ernährung muss die hohe Energie ausgeglichen werden.',
    imageUrl: '/breeds/australian-shepherd.webp',
  },
  {
    slug: 'cocker-spaniel',
    name: 'Cocker Spaniel',
    alternativeNames: ['English Cocker'],
    size: 'mittel',
    weightMin: '12',
    weightMax: '15',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Ohrenentzündungen', 'Augenprobleme', 'Übergewicht', 'Hauterkrankungen'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Cocker neigen zu Übergewicht. Hochwertige Proteine, Omega-3 für das Fell.',
    description: 'Der Cocker Spaniel ist sanftmütig und gesellig. Pflegeintensives Fell und Anfälligkeit für Ohrenentzündungen erfordern gezielte Ernährung.',
    imageUrl: '/breeds/cocker-spaniel.webp',
  },
  {
    slug: 'malteser',
    name: 'Malteser',
    alternativeNames: ['Maltese'],
    size: 'klein',
    weightMin: '3',
    weightMax: '4',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Zahnprobleme', 'Patellaluxation', 'Augenprobleme', 'Hypoglykämie'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Mini-Pellets. Hochwertiges Futter für das prachtvolle weiße Fell. Kleine, häufige Mahlzeiten.',
    description: 'Der Malteser ist ein eleganter Begleithund mit langem, weißem Fell. Spezielles Futter für Fell und Zähne ist empfehlenswert.',
    imageUrl: '/breeds/malteser.webp',
  },
  {
    slug: 'rottweiler',
    name: 'Rottweiler',
    alternativeNames: ['Rotti'],
    size: 'sehrgross',
    weightMin: '42',
    weightMax: '60',
    lifeExpectancy: 10,
    activityLevel: 'mittel',
    commonHealthIssues: ['Hüftdysplasie', 'Ellenbogendysplasie', 'Magendrehung', 'Krebsdisposition'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Große Rasse, langsame Reife. Welpen NICHT überfüttern (Gelenke!). 2 Mahlzeiten täglich, Magendrehung-Risiko beachten.',
    description: 'Der Rottweiler ist kräftig und ausgeglichen. Wegen Größe und Gelenkanfälligkeit ist die Ernährung – besonders im Welpenalter – kritisch.',
    imageUrl: '/breeds/rottweiler.webp',
  },
  {
    slug: 'boxer',
    name: 'Boxer',
    alternativeNames: [],
    size: 'gross',
    weightMin: '25',
    weightMax: '32',
    lifeExpectancy: 10,
    activityLevel: 'hoch',
    commonHealthIssues: ['Herzerkrankungen', 'Krebs', 'Magendrehung', 'Hüftdysplasie'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Boxer haben oft Allergien. Monoprotein-Futter erwägen. 2 Mahlzeiten, Magendrehung-Risiko.',
    description: 'Verspielt, treu und ausdauernd. Boxer brauchen wegen Allergieneigung und Herzproblemen besonders hochwertige Ernährung.',
    imageUrl: '/breeds/boxer.webp',
  },
  {
    slug: 'yorkshire-terrier',
    name: 'Yorkshire Terrier',
    alternativeNames: ['Yorkie'],
    size: 'klein',
    weightMin: '2',
    weightMax: '4',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Zahnprobleme', 'Patellaluxation', 'Tracheakollaps', 'Hypoglykämie'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Mini-Größe braucht kleine Pellets und häufige Mahlzeiten (3-4x täglich). Zahngesundheit fördern.',
    description: 'Klein aber selbstbewusst – der Yorkie ist ein temperamentvoller Begleiter. Spezial-Futter für kleine Rassen ist Pflicht.',
    imageUrl: '/breeds/yorkshire-terrier.webp',
  },
  {
    slug: 'shih-tzu',
    name: 'Shih Tzu',
    alternativeNames: [],
    size: 'klein',
    weightMin: '4',
    weightMax: '7',
    lifeExpectancy: 14,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Augenprobleme', 'Atemprobleme (Brachycephalie)', 'Hüftdysplasie', 'Allergien'],
    recommendedProteinPercentage: 24,
    recommendedFatPercentage: 12,
    feedingNotes: 'Niedrig-aktive Rasse, weniger Kalorien. Hypoallergen-Futter bei Allergien sinnvoll.',
    description: 'Der Shih Tzu ist ein gemütlicher Begleithund. Wegen Atemproblemen und Allergieneigung sollte das Futter sorgfältig gewählt werden.',
    imageUrl: '/breeds/shih-tzu.webp',
  },
  {
    slug: 'havaneser',
    name: 'Havaneser',
    alternativeNames: [],
    size: 'klein',
    weightMin: '4',
    weightMax: '8',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Patellaluxation', 'Augenprobleme', 'Herzerkrankungen', 'Taubheit'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 13,
    feedingNotes: 'Familienhund mit gutem Appetit. Hochwertiges Futter für das gepflegte Fell, Omega-Fettsäuren.',
    description: 'Lebhaft und kinderlieb. Havaneser brauchen ein qualitatives Futter, das Fell und Energie unterstützt.',
    imageUrl: '/breeds/havaneser.webp',
  },
  {
    slug: 'pudel',
    name: 'Pudel',
    alternativeNames: ['Poodle'],
    size: 'mittel',
    weightMin: '4',
    weightMax: '25',
    lifeExpectancy: 14,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Magendrehung (große Variante)', 'Epilepsie'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Größe variiert stark (Toy bis Großpudel). Tagesmenge an Größe anpassen. Hochwertiges Futter für das Fell.',
    description: 'Intelligent, elegant, vielseitig. Der Pudel kommt in vier Größen – die Ernährung muss entsprechend dimensioniert werden.',
    imageUrl: '/breeds/pudel.webp',
  },
  {
    slug: 'zwergpinscher',
    name: 'Zwergpinscher',
    alternativeNames: ['Min Pin'],
    size: 'klein',
    weightMin: '4',
    weightMax: '5',
    lifeExpectancy: 14,
    activityLevel: 'hoch',
    commonHealthIssues: ['Patellaluxation', 'Augenprobleme', 'Diabetes', 'Herzerkrankungen'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Aktiver kleiner Hund. Hochwertige Proteine, Diabetes-Risiko beachten – keine Zuckerzusätze.',
    description: 'Klein, schnell, selbstbewusst. Der Zwergpinscher braucht qualitatives Futter ohne Füllstoffe.',
    imageUrl: '/breeds/zwergpinscher.webp',
  },
  {
    slug: 'cavalier-king-charles',
    name: 'Cavalier King Charles Spaniel',
    alternativeNames: ['Cavalier'],
    size: 'klein',
    weightMin: '5',
    weightMax: '8',
    lifeExpectancy: 12,
    activityLevel: 'mittel',
    commonHealthIssues: ['Mitralklappen-Erkrankung', 'Syringomyelie', 'Hüftdysplasie', 'Augenprobleme'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Wegen Herzerkrankungsrisiko: Taurin und L-Carnitin-haltiges Futter wählen. Natriumarm bei Herzproblemen.',
    description: 'Sanft, freundlich, ein Familienhund par excellence. Wegen der Herzanfälligkeit der Rasse ist die Futterwahl besonders wichtig.',
    imageUrl: '/breeds/cavalier-king-charles.webp',
  },
  {
    slug: 'berner-sennenhund',
    name: 'Berner Sennenhund',
    alternativeNames: ['Berner'],
    size: 'sehrgross',
    weightMin: '40',
    weightMax: '55',
    lifeExpectancy: 8,
    activityLevel: 'mittel',
    commonHealthIssues: ['Krebs (häufig)', 'Hüftdysplasie', 'Magendrehung', 'Degenerative Myelopathie'],
    recommendedProteinPercentage: 24,
    recommendedFatPercentage: 12,
    feedingNotes: 'Große Rasse, langsame Reife. Welpenfutter mit kontrolliertem Calcium für gesunde Gelenke. 2-3 Mahlzeiten.',
    description: 'Liebevoll und ruhig, leider mit kurzer Lebenserwartung. Hochwertige Ernährung kann viel zur Lebensqualität beitragen.',
    imageUrl: '/breeds/berner-sennenhund.webp',
  },
  {
    slug: 'dobermann',
    name: 'Dobermann',
    alternativeNames: ['Doberman Pinscher'],
    size: 'gross',
    weightMin: '32',
    weightMax: '45',
    lifeExpectancy: 11,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['DCM (Herzerkrankung)', 'Hüftdysplasie', 'Wobbler-Syndrom', 'von-Willebrand-Krankheit'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Hohes DCM-Risiko: Taurin und L-Carnitin im Futter wichtig. Hochwertige Proteine.',
    description: 'Elegant, schnell, intelligent. Der Dobermann braucht hochwertiges Futter mit herzschützenden Nährstoffen.',
    imageUrl: '/breeds/dobermann.webp',
  },
  {
    slug: 'bordeauxdogge',
    name: 'Bordeauxdogge',
    alternativeNames: ['Dogue de Bordeaux'],
    size: 'sehrgross',
    weightMin: '54',
    weightMax: '65',
    lifeExpectancy: 7,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Herzerkrankungen', 'Hüftdysplasie', 'Atemprobleme', 'Hauterkrankungen'],
    recommendedProteinPercentage: 24,
    recommendedFatPercentage: 12,
    feedingNotes: 'Sehr großer Hund. Welpenphase besonders kritisch (langsames Wachstum fördern). 2-3 Mahlzeiten täglich.',
    description: 'Massiv und gutmütig. Bordeauxdoggen brauchen wegen ihrer Größe und Anfälligkeiten eine besonders durchdachte Ernährung.',
    imageUrl: '/breeds/bordeauxdogge.webp',
  },
  {
    slug: 'rhodesian-ridgeback',
    name: 'Rhodesian Ridgeback',
    alternativeNames: ['Ridgeback'],
    size: 'gross',
    weightMin: '32',
    weightMax: '40',
    lifeExpectancy: 11,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Dermoid Sinus', 'Magendrehung', 'Schilddrüsenunterfunktion'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Aktive Rasse mit gutem Appetit. Hochwertige Proteine, 2 Mahlzeiten gegen Magendrehung.',
    description: 'Athletisch, mutig, unabhängig. Der Ridgeback braucht ein energiereiches, qualitatives Futter.',
    imageUrl: '/breeds/rhodesian-ridgeback.webp',
  },
  {
    slug: 'weimaraner',
    name: 'Weimaraner',
    alternativeNames: [],
    size: 'gross',
    weightMin: '25',
    weightMax: '40',
    lifeExpectancy: 11,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Magendrehung', 'Hüftdysplasie', 'von-Willebrand-Krankheit', 'Hypothyreose'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 15,
    feedingNotes: 'Sehr aktive Rasse. 2-3 Mahlzeiten (Magendrehung-Risiko!), nach dem Fressen Ruhepause.',
    description: 'Eleganter, vielseitiger Jagdhund. Weimaraner brauchen viel Bewegung und entsprechend energiereiches Futter.',
    imageUrl: '/breeds/weimaraner.webp',
  },
  {
    slug: 'dalmatiner',
    name: 'Dalmatiner',
    alternativeNames: ['Dalmatian'],
    size: 'mittel',
    weightMin: '20',
    weightMax: '32',
    lifeExpectancy: 12,
    activityLevel: 'hoch',
    commonHealthIssues: ['Harnsteine (Urat)', 'Taubheit', 'Hüftdysplasie', 'Allergien'],
    recommendedProteinPercentage: 22,
    recommendedFatPercentage: 12,
    feedingNotes: 'BESONDERHEIT: Purinarme Ernährung wegen Harnsteine-Risiko. Spezial-Futter für Dalmatiner verfügbar.',
    description: 'Die schwarzen Punkte machen ihn unverwechselbar. Wegen der Urat-Stoffwechselbesonderheit ist die Ernährung speziell.',
    imageUrl: '/breeds/dalmatiner.webp',
  },
  {
    slug: 'siberian-husky',
    name: 'Siberian Husky',
    alternativeNames: ['Husky'],
    size: 'mittel',
    weightMin: '16',
    weightMax: '27',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Augenprobleme', 'Hüftdysplasie', 'Zinkmangel', 'Schilddrüsenprobleme'],
    recommendedProteinPercentage: 28,
    recommendedFatPercentage: 16,
    feedingNotes: 'Sehr effizienter Stoffwechsel – braucht weniger Futter als andere große Hunde! Hochfettig, hochproteinhaltig.',
    description: 'Wölfischer Schlittenhund mit unerschöpflicher Energie. Huskies brauchen energiereiches Futter trotz geringer Gesamtmenge.',
    imageUrl: '/breeds/siberian-husky.webp',
  },
  {
    slug: 'alaskan-malamute',
    name: 'Alaskan Malamute',
    alternativeNames: ['Malamute'],
    size: 'sehrgross',
    weightMin: '34',
    weightMax: '43',
    lifeExpectancy: 12,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Hypothyreose', 'Polyneuropathie'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 16,
    feedingNotes: 'Großer Arbeitshund. Hochkalorisches Futter, kontrollierte Wachstumsphase bei Welpen.',
    description: 'Der größere Verwandte des Huskies. Eine majestätische Erscheinung mit echtem Arbeitscharakter und entsprechendem Energiebedarf.',
    imageUrl: '/breeds/alaskan-malamute.webp',
  },
  {
    slug: 'shiba-inu',
    name: 'Shiba Inu',
    alternativeNames: [],
    size: 'mittel',
    weightMin: '7',
    weightMax: '11',
    lifeExpectancy: 14,
    activityLevel: 'hoch',
    commonHealthIssues: ['Allergien', 'Glaukom', 'Patellaluxation', 'Hüftdysplasie'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Allergie-anfällig – Monoprotein-Futter, getreidefrei oft sinnvoll. Hochwertige Zutaten.',
    description: 'Selbstbewusst, intelligent, fast katzenartig. Der Shiba Inu ist Japans beliebteste Rasse mit ausgeprägter Allergieneigung.',
    imageUrl: '/breeds/shiba-inu.webp',
  },
  {
    slug: 'akita-inu',
    name: 'Akita Inu',
    alternativeNames: ['Akita'],
    size: 'gross',
    weightMin: '32',
    weightMax: '50',
    lifeExpectancy: 11,
    activityLevel: 'mittel',
    commonHealthIssues: ['Autoimmunerkrankungen', 'Hüftdysplasie', 'Sebadenitis', 'Hypothyreose'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 14,
    feedingNotes: 'Anfälligkeit für Autoimmunerkrankungen – hochwertiges Futter ohne unnötige Zusätze. Fischbasis oft gut verträglich.',
    description: 'Würdevoll, loyal, japanisches Nationalsymbol. Der Akita braucht qualitatives Futter, das das Immunsystem nicht überlastet.',
    imageUrl: '/breeds/akita-inu.webp',
  },
  {
    slug: 'chow-chow',
    name: 'Chow-Chow',
    alternativeNames: ['Chow'],
    size: 'mittel',
    weightMin: '20',
    weightMax: '32',
    lifeExpectancy: 11,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Hüftdysplasie', 'Entropium', 'Patellaluxation', 'Hypothyreose'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Wenig aktiv, weniger Kalorien. Hochwertiges Futter für das dichte Fell.',
    description: 'Stolz und distanziert mit löwenartiger Mähne. Der Chow-Chow braucht keine großen Mengen, aber Qualität.',
    imageUrl: '/breeds/chow-chow.webp',
  },
  {
    slug: 'pekinese',
    name: 'Pekinese',
    alternativeNames: ['Peking'],
    size: 'klein',
    weightMin: '3',
    weightMax: '6',
    lifeExpectancy: 13,
    activityLevel: 'niedrig',
    commonHealthIssues: ['Brachycephales Syndrom', 'Augenprobleme', 'Wirbelsäulenprobleme', 'Hauterkrankungen'],
    recommendedProteinPercentage: 24,
    recommendedFatPercentage: 12,
    feedingNotes: 'Sehr wenig Bewegungsbedarf – Kalorien niedrig halten. Mini-Pellets wegen Kurzschnauze.',
    description: 'Würdevoll, eigensinnig, fast katzenhaft. Der Pekinese braucht angepasstes Futter wegen seiner Kurzschnauze.',
    imageUrl: '/breeds/pekinese.webp',
  },
  {
    slug: 'lhasa-apso',
    name: 'Lhasa Apso',
    alternativeNames: [],
    size: 'klein',
    weightMin: '6',
    weightMax: '8',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Augenprobleme', 'Hüftdysplasie', 'Nierenerkrankungen', 'Hauterkrankungen'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 13,
    feedingNotes: 'Hochwertiges Futter für das prachtvolle Fell. Bei Nierenanfälligkeit phosphatarmes Futter ggf. sinnvoll.',
    description: 'Tibetischer Wächterhund mit langem Fell. Der Lhasa Apso braucht qualitative Ernährung für sein eindrucksvolles Haar.',
    imageUrl: '/breeds/lhasa-apso.webp',
  },
  {
    slug: 'bichon-frise',
    name: 'Bichon Frisé',
    alternativeNames: ['Bichon'],
    size: 'klein',
    weightMin: '3',
    weightMax: '6',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Allergien', 'Patellaluxation', 'Augenprobleme', 'Zahnprobleme'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 13,
    feedingNotes: 'Allergie-anfällig: Hypoallergen-Futter oft besser. Hochwertige Zutaten für das weiße Fell.',
    description: 'Fröhlich, verspielt, das weiße Pulver-Puff. Bichon Frisés haben oft Hautprobleme – das richtige Futter hilft.',
    imageUrl: '/breeds/bichon-frise.webp',
  },
  {
    slug: 'whippet',
    name: 'Whippet',
    alternativeNames: [],
    size: 'mittel',
    weightMin: '7',
    weightMax: '14',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Herzerkrankungen', 'Augenprobleme', 'Schilddrüsenunterfunktion', 'Anästhesie-Empfindlichkeit'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Schlanker Athlet – nicht überfüttern. Hochwertige Proteine für die Muskulatur.',
    description: 'Eleganter Sprinter, sanft und genügsam. Der Whippet braucht hochwertiges, nicht zu kalorienreiches Futter.',
    imageUrl: '/breeds/whippet.webp',
  },
  {
    slug: 'greyhound',
    name: 'Greyhound',
    alternativeNames: ['Windhund'],
    size: 'gross',
    weightMin: '25',
    weightMax: '40',
    lifeExpectancy: 11,
    activityLevel: 'mittel',
    commonHealthIssues: ['Magendrehung', 'Herzerkrankungen', 'Knochenkrebs', 'Anästhesie-Risiko'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Trotz Größe relativ wenig Energiebedarf außerhalb des Trainings. Hochwertige Proteine, 2 Mahlzeiten.',
    description: 'Der schnellste Hund der Welt – im Alltag jedoch ruhig. Die Ernährung muss zur Aktivität passen, nicht zur Größe.',
    imageUrl: '/breeds/greyhound.webp',
  },
  {
    slug: 'irish-setter',
    name: 'Irish Setter',
    alternativeNames: [],
    size: 'gross',
    weightMin: '24',
    weightMax: '32',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Magendrehung', 'Hüftdysplasie', 'Epilepsie', 'Augenprobleme'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Sehr aktive Rasse – hoher Energiebedarf. 2-3 Mahlzeiten, Magendrehung beachten.',
    description: 'Rot-glänzend, energiegeladen, gesellig. Der Irish Setter braucht ein hochwertiges, energiereiches Futter.',
    imageUrl: '/breeds/irish-setter.webp',
  },
  {
    slug: 'magyar-vizsla',
    name: 'Magyar Vizsla',
    alternativeNames: ['Vizsla', 'Ungarischer Vorstehhund'],
    size: 'gross',
    weightMin: '20',
    weightMax: '30',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonheart: ['Hüftdysplasie', 'Epilepsie', 'Augenprobleme', 'Schilddrüsenprobleme'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Hochaktiv, braucht energiereiches Futter. Eher schlanker Typ – Übergewicht vermeiden.',
    description: 'Vielseitiger Jagdhund mit goldenem Fell. Vizslas brauchen Auslastung und entsprechendes Futter.',
    imageUrl: '/breeds/magyar-vizsla.webp',
  },
  {
    slug: 'samojede',
    name: 'Samojede',
    alternativeNames: ['Samoyed'],
    size: 'gross',
    weightMin: '16',
    weightMax: '30',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Diabetes', 'Nierenerkrankungen'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Dichtes Fell braucht Omega-Fettsäuren. Bei Diabetes-Risiko Zucker meiden.',
    description: 'Strahlend weiß mit dem typischen „Samojeden-Lächeln". Eine arbeitsfreudige Rasse mit speziellen Pflegeansprüchen.',
    imageUrl: '/breeds/samojede.webp',
  },
  {
    slug: 'english-setter',
    name: 'English Setter',
    alternativeNames: [],
    size: 'gross',
    weightMin: '20',
    weightMax: '36',
    lifeExpectancy: 12,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Hypothyreose', 'Taubheit', 'Allergien'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Anfällig für Allergien – Monoprotein oft sinnvoll. Aktive Rasse, hoher Energiebedarf.',
    description: 'Elegant und arbeitsfreudig, der English Setter ist ein klassischer Jagdhund mit ruhigem Temperament.',
    imageUrl: '/breeds/english-setter.webp',
  },
  {
    slug: 'pointer',
    name: 'Pointer',
    alternativeNames: ['English Pointer'],
    size: 'gross',
    weightMin: '20',
    weightMax: '34',
    lifeExpectancy: 13,
    activityLevel: 'sehrhoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Hauterkrankungen', 'Epilepsie'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Sehr aktiv – energiereiches Futter. Hochwertige Proteine für Muskelaufbau.',
    description: 'Athletisch, schnell, ausdauernd. Der Pointer braucht qualitatives Futter, das mit seiner Energie mithält.',
    imageUrl: '/breeds/pointer.webp',
  },
  {
    slug: 'labradoodle',
    name: 'Labradoodle',
    alternativeNames: [],
    size: 'gross',
    weightMin: '20',
    weightMax: '30',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Ohrenentzündungen', 'Allergien'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Mix-Rasse: Eigenschaften variieren. Hochwertiges Futter, bei Allergien anpassen.',
    description: 'Labrador × Pudel: Familienfreundlich, intelligent, oft hypoallergen. Ein Designer-Hund mit echten Qualitäten.',
    imageUrl: '/breeds/labradoodle.webp',
  },
  {
    slug: 'goldendoodle',
    name: 'Goldendoodle',
    alternativeNames: [],
    size: 'gross',
    weightMin: '15',
    weightMax: '32',
    lifeExpectancy: 13,
    activityLevel: 'hoch',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Allergien', 'Ohrenentzündungen'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Allergiefreundliche Sorten oft gut. Hochwertiges Futter für Energie und Fell.',
    description: 'Golden Retriever × Pudel: Verspielt, anhänglich, familientauglich. Beliebter Hybrid mit treuen Charakter.',
    imageUrl: '/breeds/goldendoodle.webp',
  },
  {
    slug: 'maltipoo',
    name: 'Maltipoo',
    alternativeNames: [],
    size: 'klein',
    weightMin: '2',
    weightMax: '7',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Patellaluxation', 'Augenprobleme', 'Zahnprobleme', 'Allergien'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Kleiner Hybrid – Mini-Pellets. Häufige kleine Mahlzeiten.',
    description: 'Malteser × Pudel: Klein, anhänglich, hypoallergen. Perfekt für Wohnungen und Allergiker.',
    imageUrl: '/breeds/maltipoo.webp',
  },
  {
    slug: 'cavapoo',
    name: 'Cavapoo',
    alternativeNames: [],
    size: 'klein',
    weightMin: '4',
    weightMax: '11',
    lifeExpectancy: 14,
    activityLevel: 'mittel',
    commonHealthIssues: ['Mitralklappen-Erkrankung', 'Patellaluxation', 'Augenprobleme', 'Allergien'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Hybrid aus Cavalier × Pudel. Wegen Herzanfälligkeit Taurin-haltiges Futter.',
    description: 'Cavalier × Pudel: Sanft, verspielt, familienfreundlich. Ein anhänglicher Designer-Hund.',
    imageUrl: '/breeds/cavapoo.webp',
  },
  {
    slug: 'cockapoo',
    name: 'Cockapoo',
    alternativeNames: [],
    size: 'mittel',
    weightMin: '5',
    weightMax: '14',
    lifeExpectancy: 14,
    activityLevel: 'hoch',
    commonHealthIssues: ['Ohrenentzündungen', 'Patellaluxation', 'Allergien', 'Augenprobleme'],
    recommendedProteinPercentage: 26,
    recommendedFatPercentage: 14,
    feedingNotes: 'Cocker × Pudel: aktive Rasse. Hochwertiges Futter, Omega-3 für das gewellte Fell.',
    description: 'Cocker Spaniel × Pudel: Verspielt, sozial, lernfreudig. Ein vielseitiger Begleithund.',
    imageUrl: '/breeds/cockapoo.webp',
  },
  {
    slug: 'bernedoodle',
    name: 'Bernedoodle',
    alternativeNames: [],
    size: 'gross',
    weightMin: '20',
    weightMax: '40',
    lifeExpectancy: 13,
    activityLevel: 'mittel',
    commonHealthIssues: ['Hüftdysplasie', 'Augenprobleme', 'Allergien', 'Krebsdisposition (vom Berner)'],
    recommendedProteinPercentage: 25,
    recommendedFatPercentage: 13,
    feedingNotes: 'Berner × Pudel-Hybrid. Hochwertiges Futter, Gelenkstoffe für die Größe.',
    description: 'Berner Sennenhund × Pudel: Sanft, verspielt, mit den besten Eigenschaften beider Rassen.',
    imageUrl: '/breeds/bernedoodle.webp',
  },
  {
    slug: 'dogo-argentino',
    name: 'Dogo Argentino',
    alternativeNames: ['Argentinische Dogge'],
    size: 'sehrgross',
    weightMin: '35',
    weightMax: '55',
    lifeExpectancy: 12,
    activityLevel: 'hoch',
    commonHealthIssues: ['Taubheit', 'Hüftdysplasie', 'Hautkrebs', 'Glaukom'],
    recommendedProteinPercentage: 27,
    recommendedFatPercentage: 14,
    feedingNotes: 'Kräftige, muskulöse Rasse. Hochwertige Proteine, kontrolliertes Welpenwachstum.',
    description: 'Mutig, athletisch, treu. Eine Listenhund-Rasse, die hochwertige Ernährung braucht.',
    imageUrl: '/breeds/dogo-argentino.webp',
  },
]

async function main() {
  console.log('🐕 BELLA — Rassen-Seed startet')
  console.log(`📊 Anzahl Rassen: ${breeds.length}`)

  for (const breed of breeds) {
    try {
      await db.insert(dogBreeds).values(breed as any).onConflictDoUpdate({
        target: dogBreeds.slug,
        set: breed as any,
      })
      console.log(`✅ ${breed.name}`)
    } catch (err: any) {
      console.error(`❌ ${breed.name}: ${err.message}`)
    }
  }

  console.log(`\n🐕 ${breeds.length} Rassen erfolgreich in DB geschrieben`)
  process.exit(0)
}

main().catch(err => { console.error(err); process.exit(1) })
