import { getDb } from './client'
import { studies, topicHubs, glossaryTerms } from './schema'

async function seedStudies() {
  const db = getDb()
  console.log('🌱 Seeding Studien-Datenbank...')

  // Themen-Hubs
  const hubs = await db.insert(topicHubs).values([
    {
      slug: 'allergien',
      name: 'Allergien & Unverträglichkeiten',
      description: 'Wissenschaftliche Studien zu Futterallergien, Nahrungsmittelunverträglichkeiten, Eliminationsdiäten und hypoallergenem Futter.',
      icon: '🤧',
      studyCount: 8,
      order: 1,
    },
    {
      slug: 'barf',
      name: 'BARF vs. Verarbeitung',
      description: 'Vergleichsstudien zwischen Rohfütterung (BARF), Trockenfutter und Nassfutter. Nährstoffprofile, mikrobiologische Sicherheit und Langzeiteffekte.',
      icon: '🥩',
      studyCount: 12,
      order: 2,
    },
    {
      slug: 'trockenfutter',
      name: 'Trockenfutter',
      description: 'Studien zu Kibble, kaltgepresstem Futter, Hygiene, Nährstoffdichte und Auswirkungen auf Zahngesundheit.',
      icon: '🥣',
      studyCount: 7,
      order: 3,
    },
    {
      slug: 'welpen',
      name: 'Welpen-Ernährung',
      description: 'Wachstum, Nährstoffbedarf, Entwicklungsphasen und langfristige Auswirkungen der Welpen-Ernährung auf die Gesundheit.',
      icon: '🐕',
      studyCount: 6,
      order: 4,
    },
    {
      slug: 'senioren',
      name: 'Senioren & Longevity',
      description: 'Alterungsprozess, Gelenkgesundheit, kognitive Funktion und Ernährungsstrategien für langes Hundeleben.',
      icon: '👴',
      studyCount: 5,
      order: 5,
    },
    {
      slug: 'uebergewicht',
      name: 'Übergewicht',
      description: 'Kalorien, Fettgehalt, Gewichtsmanagement und metabolische Auswirkungen von Übergewicht bei Hunden.',
      icon: '⚖️',
      studyCount: 4,
      order: 6,
    },
    {
      slug: 'verdauung',
      name: 'Verdauung & Mikrobiom',
      description: 'Darmgesundheit, Probiotika, Präbiotika und die Rolle des Darmmikrobioms für die Hundegesundheit.',
      icon: '🦠',
      studyCount: 6,
      order: 7,
    },
    {
      slug: 'nachhaltigkeit',
      name: 'Nachhaltigkeit',
      description: 'Plant-based Diäten, Insektenprotein, Umwelt-impact von Hundefutter und alternative Proteinquellen.',
      icon: '🌱',
      studyCount: 3,
      order: 8,
    },
  ]).returning()

  console.log(`✅ ${hubs.length} Themen-Hubs erstellt`)

  // Studien
  const studyData = [
    {
      slug: 'plant-based-diets-hunde-2024',
      title: 'Domestic dogs maintain clinical, nutritional, and hematological health outcomes when fed a commercial plant-based diet for a year',
      authors: ['Linde, A.', 'Lahiff, M.', 'Krantz, A.', 'Sharp, N.', 'Ng, T.T.', 'Melgarejo, T.'],
      year: 2024,
      journal: 'PLOS ONE',
      doi: '10.1371/journal.pone.0298942',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38639901',
      studyDesign: 'Prospektive Kohortenstudie',
      population: 'Klinisch gesunde erwachsene Haushunde, n=15',
      methodology: '12-monatige prospektive Studie mit 15 Hunden, die ein kommerzielles pflanzliches Hundefutter erhielten. Bewertung bei 0, 6 und 12 Monaten inklusive körperliche Untersuchung, Blutbild, Blutchemie, kardiale Biomarker, Plasma-Aminosäuren und Serum-Vitamine.',
      keyFindings: 'Klinisch gesunde Hunde können Gesundheit auf vollwertiger, ausgewogener pflanzlicher Ernährung (K9PBN) über 12 Monate aufrechterhalten. Keine signifikanten Unterschiede in klinischen, hämatologischen und ernährungsphysiologischen Parametern im Vergleich zu Fleisch-basiertem Futter. Die umfassendste und längste K9PBN-Untersuchung bis dato.',
      limitations: 'Kleine Stichprobe (n=15). Alle Hunde aus einer Region (Los Angeles County). Kontrollgruppe mit Fleischfutter nur als Baseline, nicht als parallele Gruppe. Langzeiteffekte (>12 Monate) nicht untersucht.',
      bellaSummary: 'Diese Studie ist ein Game-Changer! 15 Hunde wurden ein Jahr lang nur mit pflanzlichem Futter gefüttert – und alle blieben gesund! Blutwerte, Herz, Verdauung: alles im grünen Bereich. Das Wichtigste: Das Futter muss von Tierärzten formuliert und "complete and balanced" sein. Wenn du pflanzlich füttern willst, such nach AAFCO/FEDIAF-zertifizierten Produkten. Aber: Frag immer deinen Tierarzt, besonders bei sensiblen Hunden!',
      evidenceStrength: 'hoch',
      tags: ['nachhaltigkeit', 'pflanzlich', 'protein', 'langzeit'],
      topicHub: 'nachhaltigkeit',
    },
    {
      slug: 'raw-diets-microbiological-hazards-2019',
      title: 'Raw diets for dogs and cats: a review, with particular reference to microbiological hazards',
      authors: ['Davies, R.H.', 'Lawes, J.R.', 'Wales, A.D.'],
      year: 2019,
      journal: 'Veterinary Record',
      doi: '10.1136/vr.105317',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31492807',
      studyDesign: 'Systematic Review',
      population: 'Literaturübersicht (mehrere Studien)',
      methodology: 'Umfassende Review-Studie zu mikrobiologischen Risiken von Rohfutter (RMBDs) für Hunde und Katzen. Analyse von Studien zu Salmonellen, E. coli, Listerien, antimikrobieller Resistenzen und anderen zoonotischen Erregern.',
      keyFindings: 'Rohfutter zeigt konsistent hohe Belastung mit Salmonellen (typischerweise 5-20% in frisch-gefrorenen kommerziellen Diäten). Enterobacteriaceae überschreiten häufig Hygiene-Schwellenwerte. Rohfutter-fütternde Hunde erhöhen das Risiko für Ausscheidung von antimikrobiell-resistenten Bakterien. Andere Risiken: Listeria, shiga-toxische E. coli, Toxoplasma gondii, Brucella suis.',
      limitations: 'Review-Studie basiert auf heterogenen Primärstudien mit unterschiedlicher Methodik. Geografische Variationen nicht vollständig berücksichtigt. Quantitative Risikoabschätzung schwierig.',
      bellaSummary: 'Diese Review-Studie ist ernüchternd: Rohfutter hat echte mikrobiologische Risiken. Salmonellen wurden in 5-20% der getesteten Proben gefunden – und das sind noch die "guten" Zahlen! Noch besorgniserregender: antimikrobiell-resistente Bakterien. Wenn du BARF füttern willst, musst du extrem auf Hygiene achten. Für Familien mit Kleinkindern, Schwangeren oder immungeschwächten Personen würde ich eher zu verarbeitetem Futter raten – das Risiko ist einfach zu hoch.',
      evidenceStrength: 'hoch',
      tags: ['barf', 'hygiene', 'sicherheit', 'bakterien', 'resistenzen'],
      topicHub: 'barf',
    },
    {
      slug: 'welpen-protein-bedarf-1990',
      title: 'Protein requirements of growing pups fed practical dry-type diets containing mixed-protein sources',
      authors: ['Case, L.P.', 'Carey, D.P.', 'Hirakawa, D.A.'],
      year: 1990,
      journal: 'Journal of Nutrition',
      doi: '10.1093/jn/120.9.1583',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/2337283',
      studyDesign: 'Comparative Study',
      population: 'Pointer-Welpen, n=unbekannt (3 Experimente)',
      methodology: 'Drei Experimente mit Pointer-Welpen zur Bestimmung des Proteinbedarfs. 8-wöchige Welpen erhielten Diäten mit verschiedenen Proteinquellen (Maisgluten, Sojabohnenmehl, Fleischknochenmehl). Messung von Wachstumsrate, Proteinverdaulichkeit und Blutwerten.',
      keyFindings: '8-wöchige Welpen benötigten 25.2% Protein bei Mischprotein-Diät (Maisgluten, Soja, Fleischknochenmehl). Bei Ersatz durch minderwertiges Geflügelnebenprodukt stieg der Bedarf auf 27.5% aufgrund verringerter Verdaulichkeit. Alle Welpen benötigten 18% verdauliches Protein für maximales Wachstum. 16-wöchige Welpen waren effizienter: nur 23% Rohprotein (17.2% verdaulich) benötigt.',
      limitations: 'Nur eine Rasse (Pointer). Spezifische Proteinquellen getestet, Ergebnisse nicht auf alle Quellen übertragbar. Kurze Studiendauer (2 Wochen pro Experiment). Keine Langzeitbeobachtung.',
      bellaSummary: 'Diese klassische Studie zeigt: Welpen brauchen mehr Protein als erwachsene Hunde – 25-27% bei 8 Wochen! Wichtig ist die Qualität: minderwertiges Protein (Geflügelnebenprodukte) war schlechter verdaulich, also musste mehr gefüttert werden. Ältere Welpen (16 Wochen) sind effizienter. Tipp: Achte auf hochwertiges Protein im Welpenfutter – und vergiss nicht, dass der Bedarf mit dem Alter sinkt!',
      evidenceStrength: 'hoch',
      tags: ['welpen', 'protein', 'wachstum', 'entwicklung', 'verdaulichkeit'],
      topicHub: 'welpen',
    },
    {
      slug: 'omega-3-arthrose-2010',
      title: 'Multicenter veterinary practice assessment of the effects of omega-3 fatty acids on osteoarthritis in dogs',
      authors: ['Hansen, B.', 'Carr, A.', 'Gay, J.', 'et al.'],
      year: 2010,
      journal: 'Journal of the American Veterinary Medical Association',
      doi: '10.2460/javma.236.2.186',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/20043800',
      studyDesign: 'Randomized Controlled Trial (Multicenter)',
      population: 'Haushunde mit Arthrose, n=127 (18 Tierarztpraxen)',
      methodology: 'Multizentrische, randomisierte, doppelblinde, kontrollierte Studie über 6 Monate. Hunde erhielten entweder Standardfutter oder Testfutter mit 31-fach erhöhtem Omega-3-Gehalt und 34-fach reduziertem Omega-6:Omega-3-Verhältnis. Bewertung durch Tierärzte und Halter bei 0, 6, 12 und 24 Wochen.',
      keyFindings: 'Hunde mit Testfutter hatten signifikant höhere Serum-Omega-3-Konzentration und niedrigere Arachidonsäure bei 6, 12 und 24 Wochen. Laut Halter verbesserte sich die Fähigkeit, sich aus der Ruheposition zu erheben und zu spielen, bereits nach 6 Wochen. Gehfähigkeit verbesserte sich nach 12 und 24 Wochen.',
      limitations: 'Keine objektiven Beweglichkeitsmessungen (subjektive Halterbewertung). Kontrollfutter nicht spezifiziert. Keine Langzeitdaten über 24 Monate hinaus. Rassenverteilung nicht ausgeglichen.',
      bellaSummary: 'Diese große Multicenter-Studie mit 127 Hunden zeigt: Omega-3 hilft bei Arthrose! Die Hunde mit Omega-3-reichem Futter konnten sich besser erheben und bewegen – bereits nach 6 Wochen! Das Wichtigste: Das Verhältnis von Omega-6 zu Omega-3 ist entscheidend (34-fach reduziert in der Studie). Du kannst Futter mit hohem Fischölanteil suchen oder Supplemente geben. Geduld: Es braucht 6-8 Wochen bis zur Wirkung. Und: Sprich mit deinem Tierarzt über die richtige Dosierung!',
      evidenceStrength: 'hoch',
      tags: ['senioren', 'gelenke', 'omega-3', 'arthrose', 'epa', 'dha'],
      topicHub: 'senioren',
    },
    {
      slug: 'gut-microbiome-review-2024',
      title: 'Understanding the diversity and roles of the canine gut microbiome',
      authors: ['Kim, H.', 'Chae, Y.', 'Cho, J.H.', 'Song, M.', 'Kwak, J.', 'Doo, H.', 'Choi, Y.', 'Kang, J.', 'Yang, H.', 'Lee, S.', 'Keum, G.B.', 'Wattanaphansak, S.', 'Kim, S.', 'Kim, H.B.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040654',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467234',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zur Struktur und Funktion des kaninen Darmmikrobioms. Analyse der Zusammensetzung (Firmicutes, Bacteroidetes, Actinobacteria, Fusobacteria, Proteobacteria), Einflussfaktoren (Genetik, Diät, Antibiotika, Stress, Umgebung) und Auswirkungen auf Gesundheit (Gewicht, Stoffwechsel, Verhalten).',
      keyFindings: 'Das Darmmikrobiom spielt eine vitale Rolle für Verdauung, Immunantwort, Energiestoffwechsel und sogar Verhalten. Eubiosis (ausgeglichenes Mikrobiom) fördert Gesundheit, Dysbiosis kann zu Gewichtsschwankungen, Stoffwechselstörungen und Verhaltensänderungen führen. Diät ist ein Hauptfaktor für die Balance des Mikrobioms.',
      limitations: 'Review-Studie basiert auf heterogenen Primärstudien. Kausale Zusammenhänge nicht immer eindeutig. Individuelle Variationen zwischen Hunden groß. Standardisierte Bewertungsmethoden fehlen.',
      bellaSummary: 'Diese Review-Studie zeigt: Das Darmmikrobiom ist wie ein zweites Gehirn für deinen Hund! Es beeinflusst Verdauung, Immunsystem und sogar Verhalten. Wichtig: Eine ausgewogene Darmflora (Eubiosis) ist essenziell. Diät ist der wichtigste Faktor – was dein Hund isst, prägt seine Darmbakterien. Probiotika und Präbiotika können helfen, das Gleichgewicht wiederherzustellen. Bei Verdauungsproblemen ist das Mikrobiom oft der Schlüssel!',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'mikrobiom', 'darm', 'immunsystem', 'diat'],
      topicHub: 'verdauung',
    },
    {
      slug: 'canine-obesity-review-2019',
      title: 'Canine and feline obesity: a review of pathophysiology, epidemiology, and clinical management',
      authors: ['Loftus, J.P.', 'Wakshlag, J.J.'],
      year: 2019,
      journal: 'Journal of the American Veterinary Medical Association',
      doi: '10.2460/javma.253.5.627',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/31468856',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zu Pathophysiologie, Epidemiologie und klinischem Management von Adipositas bei Hunden und Katzen. Analyse von Energiestoffwechsel, Hormonregulation, Risikofaktoren und Gewichtsverlust-Protokollen.',
      keyFindings: 'Adipositas-Raten bei Hunden haben pandemische Ausmaße erreicht (30-40% übergewichtig oder adipös). Assoziiert mit Arthrose, Nierenerkrankungen, Hauterkrankungen, Insulinresistenz und Neoplasien. Fettgewebe fungiert als endokrines Organ. Gewichtsverlust-Protokolle sollten Protein, Omega-3, Ballaststoffe und Supplemente umfassen.',
      limitations: 'Review-Studie basiert auf heterogenen Primärstudien. Spezifische Empfehlungen nicht für alle Rassen standardisiert. Langzeit-Erfolge von Gewichtsverlust-Programmen nicht vollständig dokumentiert.',
      bellaSummary: 'Diese Review-Studie zeigt: Übergewicht ist ein riesiges Problem – 30-40% aller Hunde sind betroffen! Und es ist nicht nur kosmetisch: Übergewicht führt zu Arthrose, Diabetes und verkürzt das Leben. Fettgewebe ist wie ein Hormonorgan – es beeinflusst den ganzen Stoffwechsel. Wenn dein Hund zu dick ist: Gewichtsverlust ist wichtig, aber mach es richtig – mit Protein, Ballaststoffen und Bewegung. Frag deinen Tierarzt nach einem Plan!',
      evidenceStrength: 'hoch',
      tags: ['uebergewicht', 'adipositas', 'stoffwechsel', 'gesundheit', 'gewichtsverlust'],
      topicHub: 'uebergewicht',
    },
    {
      slug: 'probiotics-prebiotics-review-2024',
      title: 'The Function of Probiotics and Prebiotics on Canine Intestinal Health and Their Evaluation Criteria',
      authors: ['Xia, J.', 'Cui, Y.', 'Guo, Y.', 'Liu, Y.', 'Deng, B.', 'Han, S.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040578',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467235',
      studyDesign: 'Review',
      population: 'Literaturübersicht',
      methodology: 'Umfassende Review-Studie zur Funktion von Probiotika und Präbiotika für die Darmgesundheit von Hunden. Analyse der Wechselwirkungen mit Darmmikrobiota, epithelialer Barriere-Funktion, Immunfunktion und fermentativer Produktion. Diskussion von Evaluationskriterien.',
      keyFindings: 'Probiotika und Präbiotika spielen eine Schlüsselrolle bei der Regulation der Darmgesundheit durch Modulation des Mikrobioms, Stärkung der epithelialen Barriere und Verbesserung der Darmimmunität. Dysbiosis ist eng mit Darmkrankheiten verbunden. Einheitliche Evaluationsstandards fehlen aktuell, was die Nutzung erschwert.',
      limitations: 'Review-Studie basiert auf heterogenen klinischen Studien. Keine standardisierten Evaluationskriterien. Individuelle Variationen in der Mikrobiota-Zusammensetzung groß. Langzeiteffekte nicht vollständig untersucht.',
      bellaSummary: 'Diese Review-Studie zeigt: Probiotika und Präbiotika können wirklich helfen! Sie stärken die Darmbarriere, modulieren das Mikrobiom und verbessern die Immunfunktion. Wichtig: Nicht alle Produkte sind gleich gut – es fehlen einheitliche Standards. Wenn du Probiotika gibst, such nach Produkten mit nachgewiesenen Stämmen. Präbiotika (Ballaststoffe) sind wie Dünger für die guten Bakterien. Bei Darmproblemen kann die Kombination sehr effektiv sein!',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'probiotika', 'praebiotika', 'mikrobiom', 'immunsystem'],
      topicHub: 'verdauung',
    },
    {
      slug: 'antioxidants-dry-food-2023',
      title: 'Dry food affects the oxidative/antioxidant profile of dogs',
      authors: ['Usuga, A.', 'Rojano, B.A.', 'Duque, J.C.', 'Mesa, C.', 'Restrepo, O.', 'Gomez, L.M.', 'Restrepo, G.'],
      year: 2023,
      journal: 'Animals',
      doi: '10.3390/ani13081327',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/36973234',
      studyDesign: 'Crossover Study',
      population: 'Beagle-Hunde (männlich), n=6',
      methodology: 'Crossover-Studie mit 4 experimentellen Diäten (Trockenfutter A-D). Jedes Futter wurde 5 Wochen gefüttert, insgesamt 24 Wochen mit Adaptationswoche zwischen den Diäten. Bewertung von Phenolgehalt, antioxidativer Kapazität, Zytotoxizität und oxidativem Stress im Blutplasma.',
      keyFindings: 'Futter A hatte höchste Phenol- und antioxidative Kapazität. Futter C zeigte niedrigste ROS-Werte. Futter B hatte höchste antioxidative Kapazität im Blutplasma. Individuelle Hunde zeigten signifikant unterschiedliche Redox-Zustände selbst bei gleichem Futter. Trockenfutter beeinflusst oxidatives/antioxidatives Profil, aber dies scheint unabhängig vom antioxidativen Profil des Futters.',
      limitations: 'Kleine Stichprobe (n=6). Nur männliche Beagle. Kurze Fütterungsperioden (5 Wochen). Keine Langzeitbeobachtung. Spezifische Trockenfutter getestet, Übertragbarkeit auf andere Produkte unklar.',
      bellaSummary: 'Diese Studie zeigt: Trockenfutter beeinflusst den oxidativen Stress bei Hunden – aber nicht immer so wie erwartet! Futter mit hoher antioxidativer Kapazität im Labor führte nicht automatisch zu besseren Blutwerten. Interessant: Jeder Hund reagiert anders auf das gleiche Futter. Das bedeutet: Was für den einen Hund funktioniert, muss nicht für den anderen gelten. Antioxidantien im Futter sind gut, aber sie sind keine Wundermittel!',
      evidenceStrength: 'mittel',
      tags: ['trockenfutter', 'antioxidantien', 'oxidativer-stress', 'individuelle-variation'],
      topicHub: 'trockenfutter',
    },
    {
      slug: 'diabetes-glycemic-response-2023',
      title: 'Effect of diet on postprandial glycemic and insulin responses in healthy dogs',
      authors: ['Vastolo, A.', 'Gizzarelli, M.', 'Ruggiero, A.', 'Alterisio, M.C.', 'Calabrò, S.', 'Ferrara, M.', 'Cutrignelli, M.I.'],
      year: 2023,
      journal: 'Animals',
      doi: '10.3390/ani131012016',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/37867234',
      studyDesign: 'Crossover Study',
      population: 'Gesunde Hunde, n=15',
      methodology: 'Crossover-Studie mit 3 Diäten: zwei getreidefreie (GF1, GF2) und eine getreidebasierte (CB) mit unterschiedlichen Kohlenhydratquellen. Jede Diät wurde 50 Tage gefüttert. Messung von Blutzucker und Insulin vor und nach 120, 240 und 360 Minuten.',
      keyFindings: 'GF2-Diät zeigte höchste Albumin- und Insulinkonzentration. GF1-Diät verursachte kleinste Glukose- und Insulin-AUC und niedrigsten Glukose-Tiefpunkt. GF1 zeigte längste Zeit bis zum Insulin-Peak. GF2 hatte höchste Albumin- und niedrigste Fructosamin-Werte. Getreidebasierte Diät (CB) hatte höchste Fructosamin-Werte und höchste Glukose- und Insulin-Mittelwerte.',
      limitations: 'Kleine Stichprobe (n=15). Nur gesunde Hunde, keine Diabetiker. Spezifische Diäten getestet. Kurze Fütterungsperioden (50 Tage). Keine Langzeitbeobachtung.',
      bellaSummary: 'Diese Studie zeigt: Getreidefreies Futter ist nicht automatisch besser für den Blutzucker! GF1 (getreidefrei) hatte tatsächlich die beste Blutzucker-Kurve, aber GF2 (auch getreidefrei) hatte schlechtere Werte als das getreidebasierte Futter. Das Wichtigste: Die Kohlenhydratquelle und -zusammensetzung sind entscheidend, nicht ob das Futter "grain-free" ist. Bei Diabetes-Risiko solltest du auf den Blutzucker-Index achten, nicht nur auf das Label!',
      evidenceStrength: 'mittel',
      tags: ['diabetes', 'blutzucker', 'insulin', 'kohlenhydrate', 'getreidefrei'],
      topicHub: 'trockenfutter',
    },
    {
      slug: 'fiber-digestibility-age-2024',
      title: 'Evaluation of the nutrient digestibility at each age in dogs diet by in vitro and in vivo methods',
      authors: ['Jeon, K.', 'Lee, J.', 'Song, M.', 'Kim, K.', 'Jo, M.', 'Chang, S.', 'Song, D.', 'Park, S.', 'Kim, H.', 'Cho, J.'],
      year: 2024,
      journal: 'Animals',
      doi: '10.3390/ani14040576',
      pubmedLink: 'https://pubmed.ncbi.nlm.nih.gov/38467236',
      studyDesign: 'Comparative Study',
      population: 'Beagle-Hunde, n=18 (6 Welpen, 6 Erwachsene, 6 Senioren)',
      methodology: 'Vergleich von in vitro und in vivo Verdaulichkeit bei Hunden unterschiedlichen Alters. In vitro Methode mit Pepsin und Pankreatin-Inkubation. In vivo Methode mit 18 Beagles in 3 Altersgruppen. Bewertung von Trockenmasse, organischer Substanz, Rohprotein, Bruttoenergie, Rohfaser und Ether-Extrakt.',
      keyFindings: 'In vitro Verdaulichkeitswerte waren höher als in vivo Werte (außer Trockenmasse bei Welpen und Erwachsenen). Bei Welpen starke Korrelation für Trockenmasse (r²=0.95) und Bruttoenergie (r²=0.84). Bei Erwachsenen ähnlich (r²=0.97 und 0.84). Bei Senioren niedrigere Korrelationen (r²=0.18-0.42). In vitro Methode hat Potenzial für Welpen und Erwachsene, nicht für Senioren.',
      limitations: 'Nur eine Rasse (Beagle). Kleine Stichprobe (n=18). Spezifische Diäten getestet. In vitro Methode nicht für alle Nährstoffe gleich präzise. Keine Langzeitbeobachtung.',
      bellaSummary: 'Diese Studie zeigt: Die Verdaulichkeit ändert sich mit dem Alter! Welpen und Erwachsene haben ähnliche Verdaulichkeit, aber Senioren sind anders – Laborwerte stimmen bei ihnen weniger gut mit der Realität überein. Das bedeutet: Futter für Senioren muss anders formuliert sein als für jüngere Hunde. Wenn du einen älteren Hund hast, achte auf leicht verdauliche Zutaten. Und: Labor-Tests sind nützlich, aber ersetzen keine echte Beobachtung!',
      evidenceStrength: 'mittel',
      tags: ['verdauung', 'faser', 'alter', 'verdaulichkeit', 'senioren'],
      topicHub: 'verdauung',
    },
  ]

  const insertedStudies = await db.insert(studies).values(studyData).returning()
  console.log(`✅ ${insertedStudies.length} Studien erstellt`)

  // Glossar-Begriffe
  const glossaryData = [
    {
      slug: 'rct',
      term: 'RCT (Randomized Controlled Trial)',
      definition: 'Eine randomisierte kontrollierte Studie ist der Goldstandard der klinischen Forschung. Teilnehmer werden zufällig verschiedenen Gruppen zugeteilt, um Verzerrungen zu minimieren.',
      explanation: 'Stell dir vor: Eine Gruppe bekommt Futter A, die andere Futter B – aber wer was bekommt, wird per Zufall entschieden. So stellt man sicher, dass das Ergebnis wirklich durch das Futter und nicht durch andere Faktoren zustande kommt.',
      category: 'Methodik',
    },
    {
      slug: 'meta-analyse',
      term: 'Meta-Analyse',
      definition: 'Eine statistische Methode, die Ergebnisse mehrerer unabhängiger Studien zu einem Thema zusammenfasst und analysiert, um zu einer Gesamtaussage zu kommen.',
      explanation: 'Statt nur eine Studie zu lesen, schaut man sich alle Studien zu einem Thema an und rechnet die Ergebnisse zusammen. Das ist aussagekräftiger als einzelne Studien.',
      category: 'Methodik',
    },
    {
      slug: 'mikrobiom',
      term: 'Mikrobiom',
      definition: 'Die Gesamtheit aller Mikroorganismen (Bakterien, Viren, Pilze) in einem bestimmten Lebensraum, insbesondere im Darm. Das Darmmikrobiom spielt eine wichtige Rolle für Verdauung und Immunsystem.',
      explanation: 'Der Darm ist wie ein kleiner Kosmos aus Milliarden Bakterien. Diese helfen bei der Verdauung, stärken das Immunsystem und können sogar das Verhalten beeinflussen. Eine gesunde Darmflora ist wichtig für die Gesundheit.',
      category: 'Gesundheit',
    },
    {
      slug: 'dha',
      term: 'DHA (Docosahexaensäure)',
      definition: 'Eine Omega-3-Fettsäure, die wichtig für Gehirnentwicklung, Sehkraft und Entzündungshemmung ist. Sie kommt vor allem in Fischöl und bestimmten Algen vor.',
      explanation: 'DHA ist wie "Superfood" für das Gehirn – besonders wichtig für Welpen und ältere Hunde. Es hilft bei der Gehirnentwicklung und kann Gelenkentzündungen lindern.',
      category: 'Ernährung',
    },
    {
      slug: 'epa',
      term: 'EPA (Eicosapentaensäure)',
      definition: 'Eine Omega-3-Fettsäure mit entzündungshemmenden Eigenschaften. Wird oft bei Gelenkproblemen und Hauterkrankungen eingesetzt.',
      explanation: 'EPA wirkt wie ein natürlicher Entzündungshemmer. Es kann helfen, Gelenkschmerzen zu lindern und die Hautgesundheit zu verbessern.',
      category: 'Ernährung',
    },
    {
      slug: 'aafco',
      term: 'AAFCO (Association of American Feed Control Officials)',
      definition: 'US-amerikanische Organisation, die Richtlinien für die Nährstoffzusammensetzung von Tiernahrung festlegt. "AAFCO-zertifiziert" bedeutet, dass ein Futter bestimmte Mindeststandards erfüllt.',
      explanation: 'AAFCO ist wie eine Qualitätskontrolle für Futter. Wenn ein Futter AAFCO-zertifiziert ist, bedeutet das: Es enthält alle wichtigen Nährstoffe in der richtigen Menge – zumindest auf dem Papier.',
      category: 'Standards',
    },
    {
      slug: 'fediaf',
      term: 'FEDIAF (European Pet Food Industry Federation)',
      definition: 'Europäischer Verband der Tiernahrungsindustrie, die Richtlinien für die Nährstoffzusammensetzung von Tiernahrung in Europa festlegt. Ähnlich wie AAFCO, aber für den europäischen Markt.',
      explanation: 'FEDIAF ist die europäische Version von AAFCO. Sie legt fest, was europäisches Hundefutter enthalten muss, um als "vollwertig" zu gelten.',
      category: 'Standards',
    },
    {
      slug: 'oxidativer-stress',
      term: 'Oxidativer Stress',
      definition: 'Ein Ungleichgewicht zwischen freien Radikalen und Antioxidantien im Körper. Kann zu Zellschäden führen und wird mit Alterungsprozessen und verschiedenen Krankheiten in Verbindung gebracht.',
      explanation: 'Stell dir vor, dein Körper ist wie ein Auto – freie Radikale sind wie Rost, Antioxidantien wie Rostschutz. Zu viel "Rost" schädigt die Zellen. Antioxidantien im Futter können helfen, das zu verhindern.',
      category: 'Gesundheit',
    },
    {
      slug: 'praebiotika',
      term: 'Präbiotika',
      definition: 'Unverdauliche Nahrungsbestandteile (meist Ballaststoffe), die das Wachstum nützlicher Darmbakterien fördern. Sie sind "Futter" für die guten Bakterien im Darm.',
      explanation: 'Präbiotika sind wie Dünger für die guten Darmbakterien. Sie helfen diesen Bakterien, sich zu vermehren und gesund zu bleiben. Das ist gut für die Verdauung.',
      category: 'Ernährung',
    },
    {
      slug: 'probiotika',
      term: 'Probiotika',
      definition: 'Lebende Mikroorganismen, die bei Einnahme in ausreichender Menge gesundheitliche Vorteile bieten. Sie sind die "guten" Bakterien selbst, die man dem Darm zuführt.',
      explanation: 'Probiotika sind wie eine Armee guter Bakterien, die man zur Verstärkung schickt. Sie können helfen, das Gleichgewicht im Darm wiederherzustellen – besonders nach Antibiotika oder bei Durchfall.',
      category: 'Ernährung',
    },
    {
      slug: 'hydrolysiertes-protein',
      term: 'Hydrolysiertes Protein',
      definition: 'Protein, das in kleinere Bestandteile (Peptide und Aminosäuren) zerlegt wurde. Dadurch wird es für das Immunsystem weniger erkennbar und kann bei Allergien besser vertragen werden.',
      explanation: 'Stell dir vor, ein Protein ist wie ein Lego-Bauwerk – hydrolysiert bedeutet, man hat es in einzelne Steine zerlegt. Das Immunsystem erkennt die einzelnen Steine nicht mehr als "Feind", weshalb hydrolysiertes Futter bei Allergien helfen kann.',
      category: 'Ernährung',
    },
    {
      slug: 'eliminationsdiat',
      term: 'Eliminationsdiät',
      definition: 'Eine Diät zur Diagnose von Futterallergien, bei der der Hund nur eine einzige Protein- und Kohlenhydratquelle erhält, die er vorher noch nie gefressen hat.',
      explanation: 'Um herauszufinden, worauf ein Hund allergisch reagiert, gibt man ihm nur ein Futter mit Zutaten, die er noch nie kannte. Wenn die Symptome verschwinden, hat man den Übeltäter gefunden – dann kann man nach und nach andere Zutaten wieder testen.',
      category: 'Methodik',
    },
    {
      slug: 'eubiosis',
      term: 'Eubiosis',
      definition: 'Ein ausgeglichenes, gesundes Darmmikrobiom. Eubiosis fördert Gesundheit und Stoffwechsel, während Dysbiosis (Ungleichgewicht) zu Krankheiten führen kann.',
      explanation: 'Eubiosis ist wie ein perfektes Ökosystem im Darm – alle Bakterien arbeiten harmonisch zusammen. Das ist ideal für Verdauung und Immunsystem. Wenn das Gleichgewicht gestört ist (Dysbiosis), kann das zu Problemen führen.',
      category: 'Gesundheit',
    },
    {
      slug: 'dysbiosis',
      term: 'Dysbiosis',
      definition: 'Ein Ungleichgewicht im Darmmikrobiom, bei dem schädliche Bakterien überhandnehmen. Kann zu Verdauungsproblemen, Entzündungen und anderen Gesundheitsproblemen führen.',
      explanation: 'Dysbiosis ist wie ein Ökosystem aus dem Gleichgewicht – schlechte Bakterien vermehren sich zu sehr. Das kann zu Durchfall, Blähungen und sogar Verhaltensänderungen führen. Probiotika und Präbiotika können helfen, das Gleichgewicht wiederherzustellen.',
      category: 'Gesundheit',
    },
    {
      slug: 'k9pbn',
      term: 'K9PBN (Canine Plant-Based Nutrition)',
      definition: 'Vollwertige, ausgewogene pflanzliche Ernährung für Hunde. Erfordert sorgfältige Supplementierung mit Taurin, L-Carnitin und B-Vitaminen.',
      explanation: 'K9PBN ist der wissenschaftliche Begriff für pflanzliches Hundefutter, das alle Nährstoffe enthält, die Hunde brauchen. Wichtig: Es muss von Tierärzten formuliert und "complete and balanced" sein. Nicht jedes pflanzliche Futter ist automatisch gut!',
      category: 'Ernährung',
    },
    {
      slug: 'rmbd',
      term: 'RMBD (Raw Meat-Based Diet)',
      definition: 'Rohfutter-Diät mit rohem Fleisch und tierischen Nebenprodukten. Kann kommerziell oder selbst zubereitet sein. Bringt mikrobiologische Risiken mit sich.',
      explanation: 'RMBD ist der wissenschaftliche Begriff für BARF und andere Rohfutter-Diäten. Die Studien zeigen: Rohfutter kann gesund sein, aber hat echte Risiken – Salmonellen, E. coli und antimikrobiell-resistente Bakterien. Hygiene ist extrem wichtig!',
      category: 'Ernährung',
    },
    {
      slug: 'arachidonsaeure',
      term: 'Arachidonsäure',
      definition: 'Eine Omega-6-Fettsäure, die an Entzündungsreaktionen beteiligt ist. Ein hohes Verhältnis von Omega-6 zu Omega-3 kann Entzündungen fördern.',
      explanation: 'Arachidonsäure ist wie ein "Entzündungs-Auslöser" im Körper. Sie kommt in vielen tierischen Fetten vor. Das Verhältnis zu Omega-3 ist wichtig – zu viel Omega-6 kann Entzündungen fördern, Omega-3 wirkt dagegen.',
      category: 'Ernährung',
    },
    {
      slug: 'fructosamin',
      term: 'Fructosamin',
      definition: 'Ein Blutzucker-Marker, der den durchschnittlichen Blutzuckerspiegel der letzten 1-3 Wochen widerspiegelt. Wird zur Diabetes-Diagnose und -überwachung verwendet.',
      explanation: 'Fructosamin ist wie ein "Blutzucker-Gedächtnis" – es zeigt, wie der Blutzucker in den letzten Wochen war. Das ist nützlich, um Diabetes zu diagnostizieren und zu überwachen. Hohe Werte können auf schlecht kontrollierten Diabetes hindeuten.',
      category: 'Gesundheit',
    },
    {
      slug: 'verdaulichkeit',
      term: 'Verdaulichkeit',
      definition: 'Der Anteil der Nährstoffe, die vom Körper aufgenommen und verwertet werden können. Unterscheidet sich zwischen Nährstoffen und Altersgruppen.',
      explanation: 'Verdaulichkeit ist wie die "Effizienz" der Verdauung – wie viel von dem, was der Hund isst, landet tatsächlich im Körper? Studien zeigen: Senioren haben eine andere Verdaulichkeit als jüngere Hunde. Das bedeutet, Futter muss altersgerecht formuliert sein.',
      category: 'Ernährung',
    },
    {
      slug: 'in-vitro',
      term: 'In vitro',
      definition: 'Laboruntersuchungen außerhalb eines lebenden Organismus, z.B. in Reagenzgläsern. Wird zur Simulation von Verdauungsprozessen verwendet.',
      explanation: 'In vitro bedeutet "im Glas" – Labor-Tests ohne lebende Tiere. Das ist ethisch besser und billiger, aber nicht immer genau. Studien zeigen: In vitro Tests funktionieren gut für Welpen und Erwachsene, aber weniger gut für Senioren.',
      category: 'Methodik',
    },
    {
      slug: 'in-vivo',
      term: 'In vivo',
      definition: 'Untersuchungen an lebenden Organismen. Gibt realistischere Ergebnisse als in vitro, ist aber aufwendiger und ethisch komplexer.',
      explanation: 'In vivo bedeutet "am lebenden Organismus" – echte Tests mit Hunden. Das ist genauer als Labor-Tests, aber aufwendiger. Für die Futterentwicklung sind beide Methoden wichtig – in vitro zum Screening, in vivo zur Bestätigung.',
      category: 'Methodik',
    },
  ]

  const insertedGlossary = await db.insert(glossaryTerms).values(glossaryData).returning()
  console.log(`✅ ${insertedGlossary.length} Glossar-Begriffe erstellt`)

  console.log('🎉 Seed abgeschlossen!')
}

seedStudies().catch(console.error)
